### ISSUE TITLE
Error in accessing ./well-known/acme/challenge/...

### ISSUE THREAD

**Issue by kshitizshankar** [Daplie/letsencrypt-express#101]
Hey.. I am not sure what I did wrong but I am not able to set it up. Every time I fire up the nodejs server, I get the following error when I try to open https://mydomain.com/api/message

```
ERROR in le-sni-auto:
Error: The CA was unable to validate the file you provisioned. 
 - https://acme-staging.api.letsencrypt.org/acme/challenge/VMmaJG0mqkF9pEHc1VzLoJ0k8VxnDOeaFzyyW8PAia0/16356173 [pending]
 - https://acme-staging.api.letsencrypt.org/acme/challenge/VMmaJG0mqkF9pEHc1VzLoJ0k8VxnDOeaFzyyW8PAia0/16356174 [pending]
 - https://acme-staging.api.letsencrypt.org/acme/challenge/VMmaJG0mqkF9pEHc1VzLoJ0k8VxnDOeaFzyyW8PAia0/16356175 [invalid]
   Invalid response from http://<mydomain.com>/.well-known/acme-challenge/8EXLO4tsxZqpUbB-1e3prw_PG7mX6Z1l5tN2VKh_HLg: "<!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN">
<html><head>
<title>404 Not Found</title>
</head><body>
<h1>Not Found</h1>
<p"
    at handleErr (/var/nodejs-apis/node_modules/le-acme-core/lib/get-certificate.js:351:17)
    at ensureValidation (/var/nodejs-apis/node_modules/le-acme-core/lib/get-certificate.js:226:16)
    at Request._callback (/var/nodejs-apis/node_modules/le-acme-core/lib/get-certificate.js:208:13)
    at Request.self.callback (/var/nodejs-apis/node_modules/request/request.js:187:22)
    at emitTwo (events.js:106:13)
    at Request.emit (events.js:191:7)
    at Request.<anonymous> (/var/nodejs-apis/node_modules/request/request.js:1048:10)
    at emitOne (events.js:96:13)
    at Request.emit (events.js:188:7)
    at IncomingMessage.<anonymous> (/var/nodejs-apis/node_modules/request/request.js:969:12)
    at emitNone (events.js:91:20)
    at IncomingMessage.emit (events.js:185:7)
    at endReadableNT (_stream_readable.js:974:12)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickCallback (internal/process/next_tick.js:98:9)

```
Am I missing something here? 
I have an apache server as well that runs at http://mydomain.com - Is that the reason? If so, how can I fix it?

Thanks a lot! :)

**Comment by coolaj86** [comment]
If you're running Apache on that domain then you need to use the command line version instead and schedule it with cron.

The official python version has more options for Apache.
