### ISSUE TITLE
loopback should be defined as function 

### ISSUE THREAD

**Issue by oliver-j** [Daplie/letsencrypt-express#103]
I am not able to generate a cert, this is the output:

```bash
le.challenges[http-01].loopback should be defined as function (opts, domain, token, keyAuthorization, cb) { ... } and should prove (by external means) that the ACME server challenge 'http-01' will succeed
le.challenges[tls-sni-01].loopback should be defined as function (opts, domain, token, keyAuthorization, cb) { ... } and should prove (by external means) that the ACME server challenge 'tls-sni-01' will succeed
Listening for ACME http-01 challenges on { address: '::', family: 'IPv6', port: 80 }
Listening for ACME tls-sni-01 challenges and serve app on { address: '::', family: 'IPv6', port: 443 }
```

```javascript
const lex = require('letsencrypt-express').create({
    server: 'staging', //'https://acme-v01.api.letsencrypt.org/directory', 
    agreeTos: true, 
    approveDomains: function approveDomains(opts, certs, cb) {
        if (certs) { 
           opts.domains = certs.altnames;
        } else {
           opts.email = 'oliver.jessner@gmail.com';
           opts.agreeTos = true;
           opts.domains = ['eu.ganescha.io'];
        }

        cb(null, { options: opts, certs: certs });
    }
});

require('http').createServer(lex.middleware(require('redirect-https')())).listen(80, function () {
  console.log('Listening for ACME http-01 challenges on', this.address());
});

require('https').createServer(lex.httpsOptions, lex.middleware(app)).listen(443, function () {
  console.log('Listening for ACME tls-sni-01 challenges and serve app on', this.address());
});
```

As far as I understand it should generate a dir called letsencrypt_config, but it doesn't. 
Thanks for every help

**Comment by glittle** [comment]
That output may be okay.  See [this comment](https://github.com/Daplie/letsencrypt-express/issues/99#issuecomment-255516236).

**Comment by oliver-j** [comment]
We had to add the dirs paths as properties, took as a few hours to figure out. 
Maybe the README needs some additional info.

```javascript
const lex = require('letsencrypt-express').create({
  server: 'https://acme-v01.api.letsencrypt.org/directory', 
  challenges: { 
     'http-01': require('le-challenge-fs').create({ webrootPath: '~/letsencrypt/var/acme-challenges' }) 
  },
  store: require('le-store-certbot').create({
    configDir: '/etc/letsencrypt',                           
    privkeyPath: ':configDir/live/:hostname/privkey.pem', 
    fullchainPath: ':configDir/live/:hostname/fullchain.pem',
    certPath: ':configDir/live/:hostname/cert.pem',    
    chainPath: ':configDir/live/:hostname/chain.pem',           
    workDir: '/var/lib/letsencrypt', 
    logsDir: '/var/log/letsencrypt',  
    webrootPath: '~/letsencrypt/srv/www/:hostname/.well-known/acme-challenge',
    debug: false
}) .... cut
```

Thanks anyway

**Comment by MatthieuHPP** [comment]
Hello,

I do have the same error message and do not see how to go further. 

`le.challenges[tls-sni-01].loopback should be defined as function (opts, domain, token, cb) { ... } and should prove (by external means) that the ACME server challenge 'tls-sni-01' will succeed
`
I had the following warning after installing greenblock-express
`npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.1.1: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})`

I am working  with Unbuntu and node 6.X. 
I see no folder "acme-challenges" in my "tmp" folder Many thanks for your help.
I tryed to modify the links but it does not work anymore.

The code I use is coming from the exemple given on github greenlock-express

```
app.use('/api', router)

const lex = require('greenlock-express').create({
  server: 'staging',
  challenges: { 'http-01': require('le-challenge-fs').create({ webrootPath: '/tmp/acme-challenges' }) },
  store: require('le-store-certbot').create({ webrootPath: '/tmp/acme-challenges' }),
  approveDomains: approveDomains
})

function approveDomains(opts, certs, cb) {
  if (certs) {
    opts.domains = certs.altnames
  }
  else {
    opts.email = 'lepxxxx@gmail.com'   // xxxx to hide true email
    opts.agreeTos = true
  }
  cb(null, { options: opts, certs: certs })
}
require('http').createServer(lex.middleware(require('redirect-https')())).listen(80, function () {
  console.log("Listening for ACME http-01 challenges on", this.address())
})

// handles your app
require('https').createServer(lex.httpsOptions, lex.middleware(app)).listen(443, function () {
  console.log("Listening for ACME tls-sni-01 challenges and serve app on", this.address())
})
```

**Comment by MatthieuHPP** [comment]
Modifying port numbers to deal with root users, the compiler works but I do have the following error and the site page is not accessible: 
```
le.challenges[tls-sni-01].loopback should be defined as function (opts, domain, token, cb) { ... } and should prove (by external means) that the ACME server challenge 'tls-sni-01' will succeed
Listening for ACME http-01 challenges on { address: '::', family: 'IPv6', port: 3000 }
Listening for ACME tls-sni-01 challenges and serve app on { address: '::', family: 'IPv6', port: 1443 }
Build completed in 4.732s

webpack built f2a2e9bb266fe1d87dcc in 4736ms
TODO: modules which depend on this module should expose this error properly but since some of them don't, I expose it here directly:
Error: [Error] letiny-core: not 200 ok
    at bodyToError (/home/matthieu/Documents/Dev_HPP/1702XX_helping-pong_nuxt/node_modules/le-acme-core/lib/get-certificate.js:55:15)
    at /home/matthieu/Documents/Dev_HPP/1702XX_helping-pong_nuxt/node_modules/le-acme-core/lib/get-certificate.js:99:20
    at Request._callback (/home/matthieu/Documents/Dev_HPP/1702XX_helping-pong_nuxt/node_modules/le-acme-core/lib/acme-client.js:113:7)
    at Request.self.callback (/home/matthieu/Documents/Dev_HPP/1702XX_helping-pong_nuxt/node_modules/request/request.js:186:22)
    at emitTwo (events.js:106:13)
    at Request.emit (events.js:191:7)
    at Request.<anonymous> (/home/matthieu/Documents/Dev_HPP/1702XX_helping-pong_nuxt/node_modules/request/request.js:1081:10)
    at emitOne (events.js:96:13)
    at Request.emit (events.js:188:7)
    at IncomingMessage.<anonymous> (/home/matthieu/Documents/Dev_HPP/1702XX_helping-pong_nuxt/node_modules/request/request.js:1001:12)
    at IncomingMessage.g (events.js:291:16)
    at emitNone (events.js:91:20)
    at IncomingMessage.emit (events.js:185:7)
    at endReadableNT (_stream_readable.js:974:12)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickCallback (internal/process/next_tick.js:98:9)
{ type: 'urn:acme:error:malformed',
  detail: 'DNS name does not have enough labels',
  status: 400 }
ERROR in le-sni-auto:
Error: [Error] letiny-core: not 200 ok
    at bodyToError (/home/matthieu/Documents/Dev_HPP/1702XX_helping-pong_nuxt/node_modules/le-acme-core/lib/get-certificate.js:55:15)
    at /home/matthieu/Documents/Dev_HPP/1702XX_helping-pong_nuxt/node_modules/le-acme-core/lib/get-certificate.js:99:20
    at Request._callback (/home/matthieu/Documents/Dev_HPP/1702XX_helping-pong_nuxt/node_modules/le-acme-core/lib/acme-client.js:113:7)
    at Request.self.callback (/home/matthieu/Documents/Dev_HPP/1702XX_helping-pong_nuxt/node_modules/request/request.js:186:22)
    at emitTwo (events.js:106:13)
    at Request.emit (events.js:191:7)
    at Request.<anonymous> (/home/matthieu/Documents/Dev_HPP/1702XX_helping-pong_nuxt/node_modules/request/request.js:1081:10)
    at emitOne (events.js:96:13)
    at Request.emit (events.js:188:7)
    at IncomingMessage.<anonymous> (/home/matthieu/Documents/Dev_HPP/1702XX_helping-pong_nuxt/node_modules/request/request.js:1001:12)
    at IncomingMessage.g (events.js:291:16)
    at emitNone (events.js:91:20)
    at IncomingMessage.emit (events.js:185:7)
    at endReadableNT (_stream_readable.js:974:12)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickCallback (internal/process/next_tick.js:98:9)
```

**Comment by insightfuls** [comment]
I don't know how to completely solve your problem, but I can contribute a few things:

- The "loopback should be defined" message is a harmless warning that can be ignored.
- Let's Encrypt will not know which port to fulfill challenges against if you change it; you MUST either use an http-01 challenge on port 80, or a tls-sni-01 challenge on port 443.
- Unless you also want to type the port number in your browser, the app must also be served on port 443 (and you must type https://). If you want to avoid typing either a port or https:// you need to run on port 80, probably redirecting to port 443.
- The example does all this as long as you don't change the ports.
- I could be wrong, but I wouldn't expect Greenlock to automatically create the webroot path. You should have created it yourself already, I think. If you want to avoid this directory entirely (which I suspect you do, as you're putting it in /tmp) then you can use a tls-sni-01 challenge which works without anything in the filesystem. Just use: `challenges: { 'tls-sni-01': require('le-challenge-sni').create({}) }`
- The 

Some thoughts:

- The 'DNS name does not have enough labels' error suggests to me you're trying to register a local hostname or something. Are you using the FQDN (fully qualified domain name) to access the server when you try it in your browser?
- Maybe just hard-code `opts.domains` in `approveDomains` for starters, to make sure you're only attempting to register the domain(s) you want.
