### ISSUE TITLE
[Sanity Check Fail]: a weird object was passed back through le.fetch to lex.fetch

### ISSUE THREAD

**Issue by owencm** [Daplie/letsencrypt-express#14]
Hi and thanks in advance for your help!

I've just tried getting this running on my server (updogapp.co) but am running into a strange set of errors. Please let me know if there's any other information I can provide to help debugging!

```
[LEX] testing mode turned on
[LEX] default server: https://acme-staging.api.letsencrypt.org/directory

###################################################
#                                                 #
#     Open up a browser and visit this server     #
#     at its domain name.                         #
#                                                 #
#                                 ENJOY!          #
#                                                 #
###################################################


Note: testing certs will be installed because .testing() was called.
      remove .testing() to get live certs.


[LEX] automatic registration handling turned on for testing.


[LEX] creating sniCallback {
  "configDir": "./letsencrypt.config",
  "debug": true,
  "webrootPath": "/tmp/acme-challenge",
  "privkeyPath": "./letsencrypt.config/live/:hostname/privkey.pem",
  "fullchainPath": "./letsencrypt.config/live/:hostname/fullchain.pem",
  "certPath": "./letsencrypt.config/live/:hostname/cert.pem",
  "chainPath": "./letsencrypt.config/live/:hostname/chain.pem",
  "server": "https://acme-staging.api.letsencrypt.org/directory",
  "letsencrypt": {
    "backend": {}
  }
}
Listen
Listen
[LEX] no certs loaded for 'www.updogapp.co'
[LE] fetch
Error: ENOENT, open './letsencrypt.config/live/www.updogapp.co/privkey.pem'
[LEX] fetch from disk result 'www.updogapp.co':
null
[LEX] 'www.updogapp.co' is not registered, requesting approval
[LEX] auto register against staging server
[LEX] 'www.updogapp.co' registration approved, attempting register
[LE] register
Error: ENOENT, open './letsencrypt.config/live/www.updogapp.co/privkey.pem'
[LE DEBUG] reg domains [ 'www.updogapp.co' ]
[LE] try email
[LE] create account
################   privkeyPath   ################
./letsencrypt.config/live/www.updogapp.co/privkey.pem
Error: ENOENT, open './letsencrypt.config/live/www.updogapp.co/privkey.pem'
get certificate
Error: ENOENT, open './letsencrypt.config/live/www.updogapp.co/privkey.pem'
[LEX] 'www.updogapp.co' register completed null null
cert is NOT looking good
Unhandled rejection TypeError: undefined is not a function
    at cacheResult (/var/www/node_modules/letsencrypt-express/lib/sni-callback.js:100:7)
    at /var/www/node_modules/letsencrypt-express/lib/sni-callback.js:134:9
    at /var/www/node_modules/letsencrypt-express/node_modules/letsencrypt/index.js:307:13
    at /var/www/node_modules/letsencrypt-express/node_modules/letsencrypt/index.js:202:26
    at tryCatcher (/var/www/node_modules/letsencrypt-express/node_modules/letsencrypt/node_modules/bluebird/js/release/util.js:11:23)
    at Promise._settlePromiseFromHandler (/var/www/node_modules/letsencrypt-express/node_modules/letsencrypt/node_modules/bluebird/js/release/promise.js:491:31)
    at Promise._settlePromise (/var/www/node_modules/letsencrypt-express/node_modules/letsencrypt/node_modules/bluebird/js/release/promise.js:548:18)
    at Promise._settlePromise0 (/var/www/node_modules/letsencrypt-express/node_modules/letsencrypt/node_modules/bluebird/js/release/promise.js:593:10)
    at Promise._settlePromises (/var/www/node_modules/letsencrypt-express/node_modules/letsencrypt/node_modules/bluebird/js/release/promise.js:676:18)
    at Promise._fulfill (/var/www/node_modules/letsencrypt-express/node_modules/letsencrypt/node_modules/bluebird/js/release/promise.js:617:18)
    at Promise._resolveCallback (/var/www/node_modules/letsencrypt-express/node_modules/letsencrypt/node_modules/bluebird/js/release/promise.js:418:57)
    at Promise._settlePromiseFromHandler (/var/www/node_modules/letsencrypt-express/node_modules/letsencrypt/node_modules/bluebird/js/release/promise.js:504:17)
    at Promise._settlePromise (/var/www/node_modules/letsencrypt-express/node_modules/letsencrypt/node_modules/bluebird/js/release/promise.js:548:18)
    at Promise._settlePromise0 (/var/www/node_modules/letsencrypt-express/node_modules/letsencrypt/node_modules/bluebird/js/release/promise.js:593:10)
    at Promise._settlePromises (/var/www/node_modules/letsencrypt-express/node_modules/letsencrypt/node_modules/bluebird/js/release/promise.js:672:18)
    at Promise._reject (/var/www/node_modules/letsencrypt-express/node_modules/letsencrypt/node_modules/bluebird/js/release/promise.js:636:18)

[LEX] write file www.updogapp.co /tmp/acme-challenge
challenge: WQR2pu99H3MopQLzgQqiBwpWvez-sHH6Tw3b5unQ1Ec
response: WQR2pu99H3MopQLzgQqiBwpWvez-sHH6Tw3b5unQ1Ec.LcQlSVTWI3TVCHWqoxj6DEF2r8BeeiHMnn9nIbOfDFo
[LEX]  GET www.updogapp.co /.well-known/acme-challenge/WQR2pu99H3MopQLzgQqiBwpWvez-sHH6Tw3b5unQ1Ec
[LEX] getChallenge /tmp/acme-challenge/WQR2pu99H3MopQLzgQqiBwpWvez-sHH6Tw3b5unQ1Ec www.updogapp.co WQR2pu99H3MopQLzgQqiBwpWvez-sHH6Tw3b5unQ1Ec
[LEX] GET challenge, response:
challenge: WQR2pu99H3MopQLzgQqiBwpWvez-sHH6Tw3b5unQ1Ec
response: WQR2pu99H3MopQLzgQqiBwpWvez-sHH6Tw3b5unQ1Ec.LcQlSVTWI3TVCHWqoxj6DEF2r8BeeiHMnn9nIbOfDFo
Validating domain ... done
[LEX] removeChallenge /tmp/acme-challenge/WQR2pu99H3MopQLzgQqiBwpWvez-sHH6Tw3b5unQ1Ec www.updogapp.co WQR2pu99H3MopQLzgQqiBwpWvez-sHH6Tw3b5unQ1Ec
Requesting certificate...
Requesting certificate: done
Successfully verified cert at https://acme-staging.api.letsencrypt.org/acme/cert/fa78790fbdf98e091b2880135471c144a11d
Requesting issuer certificate...
Requesting issuer certificate: done
got certificate!
################   privkeyPath   ################
./letsencrypt.config/live/www.updogapp.co/privkey.pem
################   privkeyPath   ################
./letsencrypt.config/live/www.updogapp.co/privkey.pem
Unhandled rejection TypeError: Cannot call method 'indexOf' of undefined
    at /var/www/node_modules/letsencrypt-express/node_modules/letsencrypt/node_modules/pyconf/index.js:131:33
    at Array.forEach (native)
    at stringifyPythonConf (/var/www/node_modules/letsencrypt-express/node_modules/letsencrypt/node_modules/pyconf/index.js:109:20)
    at Object.writePythonConfFile [as writeFile] (/var/www/node_modules/letsencrypt-express/node_modules/letsencrypt/node_modules/pyconf/index.js:157:3)
    at Object.tryCatcher (/var/www/node_modules/letsencrypt-express/node_modules/letsencrypt/node_modules/bluebird/js/release/util.js:11:23)
    at Object.ret [as writeFileAsync] (eval at <anonymous> (/var/www/node_modules/letsencrypt-express/node_modules/letsencrypt/node_modules/bluebird/js/release/promisify.js:184:12), <anonymous>:12:39)
    at /var/www/node_modules/letsencrypt-express/node_modules/letsencrypt/lib/core.js:112:19
    at tryCatcher (/var/www/node_modules/letsencrypt-express/node_modules/letsencrypt/node_modules/bluebird/js/release/util.js:11:23)
    at Promise._settlePromiseFromHandler (/var/www/node_modules/letsencrypt-express/node_modules/letsencrypt/node_modules/bluebird/js/release/promise.js:491:31)
    at Promise._settlePromise (/var/www/node_modules/letsencrypt-express/node_modules/letsencrypt/node_modules/bluebird/js/release/promise.js:548:18)
    at Promise._settlePromise0 (/var/www/node_modules/letsencrypt-express/node_modules/letsencrypt/node_modules/bluebird/js/release/promise.js:593:10)
    at Promise._settlePromises (/var/www/node_modules/letsencrypt-express/node_modules/letsencrypt/node_modules/bluebird/js/release/promise.js:676:18)
    at Promise._fulfill (/var/www/node_modules/letsencrypt-express/node_modules/letsencrypt/node_modules/bluebird/js/release/promise.js:617:18)
    at /var/www/node_modules/letsencrypt-express/node_modules/letsencrypt/node_modules/bluebird/js/release/nodeback.js:42:21
    at /var/www/node_modules/letsencrypt-express/node_modules/mkdirp/index.js:48:26
    at Object.oncomplete (fs.js:107:15)

[LEX] no certs loaded for 'www.updogapp.co'
[LE] fetch
[LEX] fetch from disk result 'www.updogapp.co':
[ 'key',
  'privkey',
  'fullchain',
  'cert',
  'chain',
  'ca',
  'privkeyPath',
  'fullchainPath',
  'certPath',
  'chainPath',
  'issuedAt',
  'lifetime',
  'expiresAt' ]
cert is looking good
[Sanity Check Fail]: a weird object was passed back through le.fetch to lex.fetch
(either missing or malformed certInfo.key and / or certInfo.fullchain)
Unhandled rejection TypeError: undefined is not a function
    at cacheResult (/var/www/node_modules/letsencrypt-express/lib/sni-callback.js:95:7)
    at /var/www/node_modules/letsencrypt-express/lib/sni-callback.js:155:9
    at /var/www/node_modules/letsencrypt-express/node_modules/letsencrypt/index.js:214:9
    at tryCatcher (/var/www/node_modules/letsencrypt-express/node_modules/letsencrypt/node_modules/bluebird/js/release/util.js:11:23)
    at Promise._settlePromiseFromHandler (/var/www/node_modules/letsencrypt-express/node_modules/letsencrypt/node_modules/bluebird/js/release/promise.js:491:31)
    at Promise._settlePromise (/var/www/node_modules/letsencrypt-express/node_modules/letsencrypt/node_modules/bluebird/js/release/promise.js:548:18)
    at Promise._settlePromise0 (/var/www/node_modules/letsencrypt-express/node_modules/letsencrypt/node_modules/bluebird/js/release/promise.js:593:10)
    at Promise._settlePromises (/var/www/node_modules/letsencrypt-express/node_modules/letsencrypt/node_modules/bluebird/js/release/promise.js:676:18)
    at Promise._fulfill (/var/www/node_modules/letsencrypt-express/node_modules/letsencrypt/node_modules/bluebird/js/release/promise.js:617:18)
    at Promise._resolveCallback (/var/www/node_modules/letsencrypt-express/node_modules/letsencrypt/node_modules/bluebird/js/release/promise.js:418:57)
    at Promise._settlePromiseFromHandler (/var/www/node_modules/letsencrypt-express/node_modules/letsencrypt/node_modules/bluebird/js/release/promise.js:504:17)
    at Promise._settlePromise (/var/www/node_modules/letsencrypt-express/node_modules/letsencrypt/node_modules/bluebird/js/release/promise.js:548:18)
    at Promise._settlePromise0 (/var/www/node_modules/letsencrypt-express/node_modules/letsencrypt/node_modules/bluebird/js/release/promise.js:593:10)
    at Promise._settlePromises (/var/www/node_modules/letsencrypt-express/node_modules/letsencrypt/node_modules/bluebird/js/release/promise.js:676:18)
    at Promise._fulfill (/var/www/node_modules/letsencrypt-express/node_modules/letsencrypt/node_modules/bluebird/js/release/promise.js:617:18)
    at PromiseArray._resolve (/var/www/node_modules/letsencrypt-express/node_modules/letsencrypt/node_modules/bluebird/js/release/promise_array.js:125:19)
```

**Comment by accSone** [comment]
Looks as this is sames as: https://github.com/Daplie/letsencrypt-express/issues/11

**Comment by coolaj86** [comment]
Closing in favor of tracking #11. I should have this fixed today.
