### ISSUE TITLE
Error: [Error] letiny-core: not 200 ok

### ISSUE THREAD

**Issue by jamesmehorter** [Daplie/letsencrypt-express#16]
Hi! Thanks so much for this! 

When I run the example (using the approveRegistration() callback) the following errors display in my console once I visit https://my.project.com:

Any idea what these are from? Something I'm doing? Thanks!

(I just updated to 1.0.8 and restarted everything/emptied the letsencrypt directory in my node project—issue still exists)

```
[LE /lib/core.js] retrieve from domainKeyPath NOT IMPLEMENTED (please file an issue to remind me about this)
[LE /lib/core.js] retrieve from domainKeyPath NOT IMPLEMENTED (please file an issue to remind me about this)
[LE /lib/core.js] retrieve from domainKeyPath NOT IMPLEMENTED (please file an issue to remind me about this)
[DEBUG le/lib/core.js] registeryAsync err
Error: [Error] letiny-core: not 200 ok
    at bodyToError (/my-project/node_modules/letsencrypt-express/node_modules/letsencrypt/node_modules/letiny-core/lib/get-certificate.js:81:15)
    at /my-project/node_modules/letsencrypt-express/node_modules/letsencrypt/node_modules/letiny-core/lib/get-certificate.js:255:20
    at Request._callback (/my-project/node_modules/letsencrypt-express/node_modules/letsencrypt/node_modules/letiny-core/lib/acme-client.js:102:7)
    at Request.self.callback (/my-project/node_modules/request/request.js:199:22)
    at Request.EventEmitter.emit (events.js:98:17)
    at Request.<anonymous> (/my-project/node_modules/request/request.js:1036:10)
    at Request.EventEmitter.emit (events.js:117:20)
    at IncomingMessage.<anonymous> (/my-project/node_modules/request/request.js:963:12)
    at IncomingMessage.EventEmitter.emit (events.js:117:20)
    at _stream_readable.js:920:16
    at process._tickCallback (node.js:415:13)
    
Unhandled rejection TypeError: undefined is not a function
    at cacheResult (/my-project/node_modules/letsencrypt-express/lib/sni-callback.js:101:7)
    at /my-project/node_modules/letsencrypt-express/lib/sni-callback.js:138:9
    at /my-project/node_modules/letsencrypt-express/node_modules/letsencrypt/index.js:298:13
    at tryCatcher (/my-project/node_modules/letsencrypt-express/node_modules/letsencrypt/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/my-project/node_modules/letsencrypt-express/node_modules/letsencrypt/node_modules/bluebird/js/release/promise.js:497:31)
    at Promise._settlePromise (/my-project/node_modules/letsencrypt-express/node_modules/letsencrypt/node_modules/bluebird/js/release/promise.js:554:18)
    at Promise._settlePromise0 (/my-project/node_modules/letsencrypt-express/node_modules/letsencrypt/node_modules/bluebird/js/release/promise.js:599:10)
    at Promise._settlePromises (/my-project/node_modules/letsencrypt-express/node_modules/letsencrypt/node_modules/bluebird/js/release/promise.js:678:18)
    at Promise._reject (/my-project/node_modules/letsencrypt-express/node_modules/letsencrypt/node_modules/bluebird/js/release/promise.js:642:18)
    at Promise._resolveCallback (/my-project/node_modules/letsencrypt-express/node_modules/letsencrypt/node_modules/bluebird/js/release/promise.js:442:14)
    at Promise._settlePromiseFromHandler (/my-project/node_modules/letsencrypt-express/node_modules/letsencrypt/node_modules/bluebird/js/release/promise.js:510:17)
    at Promise._settlePromise (/my-project/node_modules/letsencrypt-express/node_modules/letsencrypt/node_modules/bluebird/js/release/promise.js:554:18)
    at Promise._settlePromise0 (/my-project/node_modules/letsencrypt-express/node_modules/letsencrypt/node_modules/bluebird/js/release/promise.js:599:10)
    at Promise._settlePromises (/my-project/node_modules/letsencrypt-express/node_modules/letsencrypt/node_modules/bluebird/js/release/promise.js:678:18)
    at Promise._reject (/my-project/node_modules/letsencrypt-express/node_modules/letsencrypt/node_modules/bluebird/js/release/promise.js:642:18)
    at Promise._settlePromise (/my-project/node_modules/letsencrypt-express/node_modules/letsencrypt/node_modules/bluebird/js/release/promise.js:569:21)
    at Promise._settlePromise0 (/my-project/node_modules/letsencrypt-express/node_modules/letsencrypt/node_modules/bluebird/js/release/promise.js:599:10)
    at Promise._settlePromises (/my-project/node_modules/letsencrypt-express/node_modules/letsencrypt/node_modules/bluebird/js/release/promise.js:678:18)
    at Promise._reject (/my-project/node_modules/letsencrypt-express/node_modules/letsencrypt/node_modules/bluebird/js/release/promise.js:642:18)
```

**Comment by jamesmehorter** [comment]
I found the following in certInfo in sni-callback.js:138

(replaced my prod url with my-testing-domain.com)

```
{ cause:
   { [Error: [Error] letiny-core: not 200 ok]
     code: 'E_STATUS_CODE',
     description:
      { type: 'urn:acme:error:rateLimited',
        detail: 'Error creating new cert :: Too many certificates already issued for: my-testing-domain.com',
        status: 429 },
     detail: 'Error creating new cert :: Too many certificates already issued for: my-testing-domain.com' },
  isOperational: true,
  code: 'E_STATUS_CODE',
  description:
   { type: 'urn:acme:error:rateLimited',
     detail: 'Error creating new cert :: Too many certificates already issued for: my-testing-domain.com',
     status: 429 },
  detail: 'Error creating new cert :: Too many certificates already issued for: my-testing-domain.com' }
```

Any idea why I would have too many certificates?

**Comment by jamesmehorter** [comment]
I was running into a mix of errors for #7 and #13 and kept starting over and trying it several times with various config changes, I'm guessing this is why I issued too many certs unintentionally.

**Comment by coolaj86** [comment]
Also, use `curl` instead of a browser for the very first certificate issuance so that you don't get 6 requests at the same time.

I don't think I can solve the too-many attempts problem generically. My best guess is to add some sort of hook for database code and let the implementer decide how to lock and unlock an attempt... and that sounds annoying so I think the better solution is that when you add a new domain you make the initial call to verify it part of the same process that adds it to your system.

**Comment by MichaelErmer** [comment]
@coolaj86 you could just initiate the first request yourself ;)
