### ISSUE TITLE
[Sanity Check Fail]: a weird object was passed back through le.fetch to lex.fetch

### ISSUE THREAD

**Issue by jamesmehorter** [Daplie/letsencrypt-express#19]
Hello I'm attempting to get the simple example working. I've just installed v1.0.8, and when I run `sudo npm start` letsencrypt-express creates an https server and when visiting mycooldomain.com for the first time I see the following structure created in my-project/letsencrypt:

(I replaced my domain name and the hashes below)
```
./letsencrypt
./letsencrypt/live
./letsencrypt/live/mycooldomain.com
./letsencrypt/live/mycooldomain.com/chain.pem
./letsencrypt/live/mycooldomain.com/chain.pem.bak
./letsencrypt/live/mycooldomain.com/fullchain.pem.bak
./letsencrypt/live/mycooldomain.com/fullchain.pem
./letsencrypt/live/mycooldomain.com/privkey.pem.bak
./letsencrypt/live/mycooldomain.com/cert.pem
./letsencrypt/live/mycooldomain.com/privkey.pem
./letsencrypt/live/mycooldomain.com/cert.pem.bak
./letsencrypt/renewal
./letsencrypt/renewal/mycooldomain.com.conf.a90d88514dfc1953.tmp
./letsencrypt/renewal/mycooldomain.com.conf.bak
./letsencrypt/renewal/mycooldomain.com.conf
./letsencrypt/accounts
./letsencrypt/accounts/acme-v01.api.letsencrypt.org
./letsencrypt/accounts/acme-v01.api.letsencrypt.org/directory
./letsencrypt/accounts/acme-v01.api.letsencrypt.org/directory/a-long-hash
./letsencrypt/accounts/acme-v01.api.letsencrypt.org/directory/a-long-hash/regr.json
./letsencrypt/accounts/acme-v01.api.letsencrypt.org/directory/a-long-hash/private_key.json
./letsencrypt/accounts/acme-v01.api.letsencrypt.org/directory/a-long-hash/meta.json
./letsencrypt/accounts/acme-v01.api.letsencrypt.org/directory/another-long-hash
./letsencrypt/accounts/acme-v01.api.letsencrypt.org/directory/another-long-hash/regr.json
./letsencrypt/accounts/acme-v01.api.letsencrypt.org/directory/another-long-hash/private_key.json
./letsencrypt/accounts/acme-v01.api.letsencrypt.org/directory/another-long-hash/meta.json
./letsencrypt/archive
./letsencrypt/archive/mycooldomain.com
./letsencrypt/archive/mycooldomain.com/chain0.pem.bak
./letsencrypt/archive/mycooldomain.com/fullchain0.pem.bak
./letsencrypt/archive/mycooldomain.com/privkey0.pem.bak
./letsencrypt/archive/mycooldomain.com/cert0.pem.bak
./letsencrypt/archive/mycooldomain.com/chain0.pem
./letsencrypt/archive/mycooldomain.com/fullchain0.pem
./letsencrypt/archive/mycooldomain.com/cert0.pem
./letsencrypt/archive/mycooldomain.com/privkey0.pem
```

However, I also now receive the following error each time I refresh mycooldomain.com:

(The [Sanity Check Fail] part and following error repeat 3 times with each request to mycooldomain.com.)
```
$ sudo npm start
ENCRYPT __ALL__ THE DOMAINS!
ENCRYPT __ALL__ THE DOMAINS!
ENCRYPT __ALL__ THE DOMAINS!
ENCRYPT __ALL__ THE DOMAINS!
[Sanity Check Fail]: a weird object was passed back through le.fetch to lex.fetch
(either missing or malformed certInfo.key and / or certInfo.fullchain)
Unhandled rejection TypeError: undefined is not a function
    at cacheResult (/my-cool-project/node_modules/letsencrypt-express/lib/sni-callback.js:99:7)
    at /my-cool-project/node_modules/letsencrypt-express/lib/sni-callback.js:165:9
    at /my-cool-project/node_modules/letsencrypt-express/node_modules/letsencrypt/index.js:215:9
    at tryCatcher (/my-cool-project/node_modules/letsencrypt-express/node_modules/letsencrypt/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/my-cool-project/node_modules/letsencrypt-express/node_modules/letsencrypt/node_modules/bluebird/js/release/promise.js:497:31)
    at Promise._settlePromise (/my-cool-project/node_modules/letsencrypt-express/node_modules/letsencrypt/node_modules/bluebird/js/release/promise.js:554:18)
    at Promise._settlePromise0 (/my-cool-project/node_modules/letsencrypt-express/node_modules/letsencrypt/node_modules/bluebird/js/release/promise.js:599:10)
    at Promise._settlePromises (/my-cool-project/node_modules/letsencrypt-express/node_modules/letsencrypt/node_modules/bluebird/js/release/promise.js:682:18)
    at Promise._fulfill (/my-cool-project/node_modules/letsencrypt-express/node_modules/letsencrypt/node_modules/bluebird/js/release/promise.js:623:18)
    at Promise._resolveCallback (/my-cool-project/node_modules/letsencrypt-express/node_modules/letsencrypt/node_modules/bluebird/js/release/promise.js:424:57)
    at Promise._settlePromiseFromHandler (/my-cool-project/node_modules/letsencrypt-express/node_modules/letsencrypt/node_modules/bluebird/js/release/promise.js:510:17)
    at Promise._settlePromise (/my-cool-project/node_modules/letsencrypt-express/node_modules/letsencrypt/node_modules/bluebird/js/release/promise.js:554:18)
    at Promise._settlePromise0 (/my-cool-project/node_modules/letsencrypt-express/node_modules/letsencrypt/node_modules/bluebird/js/release/promise.js:599:10)
    at Promise._settlePromises (/my-cool-project/node_modules/letsencrypt-express/node_modules/letsencrypt/node_modules/bluebird/js/release/promise.js:682:18)
    at Promise._fulfill (/my-cool-project/node_modules/letsencrypt-express/node_modules/letsencrypt/node_modules/bluebird/js/release/promise.js:623:18)
    at PromiseArray._resolve (/my-cool-project/node_modules/letsencrypt-express/node_modules/letsencrypt/node_modules/bluebird/js/release/promise_array.js:125:19)
```

FYI, The browser displays ~~HTTPS~~ with my testing output text. If I view the certificate (click on ~~HTTPS~~) I see:
```
The identity of this website has not been verified. 
Server's certificate does not match the URL. 
Your connection to mycooldomain.com is encrypted using an obsolete cipher suite.
```

Any ideas??

**Comment by jamesmehorter** [comment]
I decided to scrap everything again and generate my keys manually this time. 

```
sudo letsencrypt certonly --standalone --config-dir /my-cool-project/letsencrypt --agree-tos --domains mycooldomain.com --email foo@bar.com

Certificates installed at:
/my-cool-project/letsencrypt/live/mycooldomain.com/privkey.pem
/my-cool-project/letsencrypt/live/mycooldomain.com/fullchain.pem
/my-cool-project/letsencrypt/live/mycooldomain.com/cert.pem
/my-cool-project/letsencrypt/live/mycooldomain.com/chain.pem
```

Keys installed, and afterwards `sudo npm start` started as expected, though soon as I visit mycooldomain.com the same error above in output to the screen. :(

**Comment by coolaj86** [comment]
I took a look at the line numbers mentioned in the error message and they don't match up with the current release.

Try nuking `node_modules/le*` and reinstalling.

Also, what version of node.js are you running? The message `Your connection to mycooldomain.com is encrypted using an obsolete cipher suite.` is concerning. That shouldn't happen in a recent version of node, even when the retrieval fails and default certificates are issued.

**Comment by jamesmehorter** [comment]
HAH! Thank you so much :) HTTPS is working flawlessly now! :) Woohoo :)

I was running node v0.10.25 (like wtf?), updated to v5.6.0. Also reinstalled letsencrypt-express (deleted the node_module/letsencrypt-express directory and ran `sudo npm install`. Then ran `sudo npm start` and the first browser connection verified as secure, and the obsolete cipher message has disappeared. Lookin' good! Thanks a lot :)
