### ISSUE TITLE
[DEBUG le/lib/core.js] registeryAsync err

### ISSUE THREAD

**Issue by fbonesso** [Daplie/letsencrypt-express#20]
I'm getting this error when I try to register a new domain:

```
[LE /lib/core.js] retrieve from domainKeyPath NOT IMPLEMENTED (please file an issue to remind me about this)
[DEBUG le/lib/core.js] registeryAsync err
Error: [Error] letiny-core: not 200 ok
    at bodyToError (/usr/share/nginx/html/node_modules/letiny-core/lib/get-certificate.js:81:15)
    at /usr/share/nginx/html/node_modules/letiny-core/lib/get-certificate.js:265:20
    at Request._callback (/usr/share/nginx/html/node_modules/letiny-core/lib/acme-client.js:102:7)
    at Request.self.callback (/usr/share/nginx/html/node_modules/request/request.js:199:22)
    at emitTwo (events.js:87:13)
    at Request.emit (events.js:172:7)
    at Request.<anonymous> (/usr/share/nginx/html/node_modules/request/request.js:1036:10)
    at emitOne (events.js:82:20)
    at Request.emit (events.js:169:7)
    at IncomingMessage.<anonymous> (/usr/share/nginx/html/node_modules/request/request.js:963:12)
    at emitNone (events.js:72:20)
    at IncomingMessage.emit (events.js:166:7)
    at endReadableNT (_stream_readable.js:905:12)
    at nextTickCallbackWith2Args (node.js:478:9)
    at process._tickCallback (node.js:392:17)

```

**Comment by fbonesso** [comment]
Also, the cert for my domain is: **localhost.daplie.com**, I'm using v 1.1.1

**Comment by coolaj86** [comment]
Put a `console.error(body);` in `node_modules/letiny-core/lib/get-certificate.js` right around line 81 and try again.

It should have output the full error message and I'd like to fix that, but unfortunately the stack isn't long enough for me to tell where it got caught up on that, so you'll have to just hard code what I suggested above for the moment.

**Comment by fbonesso** [comment]
`detail: 'Error creating new cert :: Too many certificates already issued for: example.com.br'`

Maybe we have some limit for the same domain?

My objective is something like that:

```
site1.example.com.br
site2.example.com.br
site3.example.com.br
site4.example.com.br
site5.example.com.br
site6.example.com.br
site7.example.com.br
```

Thanks for helping!

**Comment by coolaj86** [comment]
About that...

See the issue here: https://github.com/publicsuffix/list/pull/74

I'm gonna close this since it's not a problem with the module.

**Comment by coolaj86** [comment]
We should finally make it into the Public Suffix List soon:

https://github.com/publicsuffix/list/pull/200
