### ISSUE TITLE
letiny-core: not 200 ok

### ISSUE THREAD

**Issue by greenec** [Daplie/letsencrypt-express#27]
I'm trying to generate certs for my domain, but I end up with an error that looks like this...

```
[DEBUG le/lib/core.js] registeryAsync err
Error: [Error] letiny-core: not 200 ok
    at bodyToError (/usr/local/lib/node_modules/letsencrypt-cli/node_modules/letiny-core/lib/get-certificate.js:81:15)
    at /usr/local/lib/node_modules/letsencrypt-cli/node_modules/letiny-core/lib/get-certificate.js:265:20
    at Request._callback (/usr/local/lib/node_modules/letsencrypt-cli/node_modules/letiny-core/lib/acme-client.js:102:7)
    at Request.self.callback (/usr/local/lib/node_modules/letsencrypt-cli/node_modules/request/request.js:199:22)
    at emitTwo (events.js:87:13)
    at Request.emit (events.js:172:7)
    at Request.<anonymous> (/usr/local/lib/node_modules/letsencrypt-cli/node_modules/request/request.js:1036:10)
    at emitOne (events.js:82:20)
    at Request.emit (events.js:169:7)
    at IncomingMessage.<anonymous> (/usr/local/lib/node_modules/letsencrypt-cli/node_modules/request/request.js:963:12)
    at emitNone (events.js:72:20)
    at IncomingMessage.emit (events.js:166:7)
    at endReadableNT (_stream_readable.js:905:12)
    at doNTCallback2 (node.js:441:9)
    at process._tickCallback (node.js:355:17)
[Error]: letsencrypt-cli
Error: [Error] letiny-core: not 200 ok
    at bodyToError (/usr/local/lib/node_modules/letsencrypt-cli/node_modules/letiny-core/lib/get-certificate.js:81:15)
    at /usr/local/lib/node_modules/letsencrypt-cli/node_modules/letiny-core/lib/get-certificate.js:265:20
    at Request._callback (/usr/local/lib/node_modules/letsencrypt-cli/node_modules/letiny-core/lib/acme-client.js:102:7)
    at Request.self.callback (/usr/local/lib/node_modules/letsencrypt-cli/node_modules/request/request.js:199:22)
    at emitTwo (events.js:87:13)
    at Request.emit (events.js:172:7)
    at Request.<anonymous> (/usr/local/lib/node_modules/letsencrypt-cli/node_modules/request/request.js:1036:10)
    at emitOne (events.js:82:20)
    at Request.emit (events.js:169:7)
    at IncomingMessage.<anonymous> (/usr/local/lib/node_modules/letsencrypt-cli/node_modules/request/request.js:963:12)
    at emitNone (events.js:72:20)
    at IncomingMessage.emit (events.js:166:7)
    at endReadableNT (_stream_readable.js:905:12)
    at doNTCallback2 (node.js:441:9)
    at process._tickCallback (node.js:355:17)
```

The script I'm using to generate the certs is...
```
sudo service apache2 stop
sudo forever stop /var/www/SocketServerChess/app-secure.js
sudo letsencrypt certonly \
  --email connor.greene2000@gmail.com \
  --standalone --agree-tos \
  --domains chessmatch.us,www.chessmatch.us \
  --config-dir /etc/letsencrypt
sudo service apache2 start
sudo forever start /var/www/SocketServerChess/app-secure.js
```

I haven't been able to find an answer yet, any help would be appreciated. Thanks!

**Comment by greenec** [comment]
I tried the script again today and ended up with this error...
```
[DEBUG le/lib/core.js] registeryAsync err
Error: ENOENT: no such file or directory, open '/etc/letsencrypt/live/chessmatch.us/cert.pem.c385618e642c5dc9.tmp'
    at Error (native)
[Error]: letsencrypt-cli
Error: ENOENT: no such file or directory, open '/etc/letsencrypt/live/chessmatch.us/cert.pem.c385618e642c5dc9.tmp'
    at Error (native)
```
Any thoughts?

**Comment by greenec** [comment]
Moved to letsencrypt-cli
