### ISSUE TITLE
Can't npm install on Windows

### ISSUE THREAD

**Issue by bushmango** [Daplie/letsencrypt-express#28]
With Python 2.7 installed, I'm running into an issue I can't get around.

I'm developing on a Windows machine and deploying to Ubuntu.

```
C:\dev\stevieweb\React\StevieBushmanCom>npm install --save letsencrypt
npm WARN package.json StevieBushmanCom@1.0.1 No repository field.
npm WARN package.json StevieBushmanCom@1.0.1 No license field.
\


> ursa@0.9.3 install C:\dev\stevieweb\React\StevieBushmanCom\node_modules\letsencrypt\node_modules\letiny-core\node_modules\ursa
> node-gyp rebuild

/
C:\dev\stevieweb\React\StevieBushmanCom\node_modules\letsencrypt\node_modules\letiny-core\node_modules\ursa>if not defined npm_config_node_gyp (node "C:\Program Files\nodejs\node_modules\npm\bin\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (node  rebuild )
Building the projects in this solution one at a time. To enable parallel build, please add the "/m" switch.
  ursaNative.cc
c:\dev\stevieweb\react\steviebushmancom\node_modules\letsencrypt\node_modules\letiny-core\node_m
odules\ursa\src\ursaNative.h(13): fatal error C1083: Cannot open include file: 'openssl/rsa.h':
No such file or directory [C:\dev\stevieweb\React\StevieBushmanCom\node_modules\letsencrypt\node
_modules\letiny-core\node_modules\ursa\build\ursaNative.vcxproj]
gyp ERR! build error
gyp ERR! stack Error: `C:\Program Files (x86)\MSBuild\14.0\bin\msbuild.exe` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\build.js:269:23)
gyp ERR! stack     at ChildProcess.emit (events.js:110:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:1074:12)
gyp ERR! System Windows_NT 6.3.9600
gyp ERR! command "node" "C:\\Program Files\\nodejs\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd C:\dev\stevieweb\React\StevieBushmanCom\node_modules\letsencrypt\node_modules\letiny-core\node_modules\ursa
gyp ERR! node -v v0.12.7
gyp ERR! node-gyp -v v2.0.1
gyp ERR! not ok
npm WARN optional dep failed, continuing ursa@0.9.3
```

**Comment by coolaj86** [comment]
python is not required at all

It looks like ursa failed to build, but that should be okay as noted here:

```
npm WARN optional dep failed, continuing ursa@0.9.3
```

npm shouldn't stop after that error, it should continue. Have you tried running after the install?

Also, I'm hoping to get a Surface Book with Windows 10 soon. If that happens I'll be able to test on Windows.

**Comment by coolaj86** [comment]
I'm going to close this because I don't see here that the install failed. I see that it had a warning about `ursa` (which is why `forge` is used as a fallback). Please re-open if there's actually error.
