### ISSUE TITLE
Certification doesn't work

### ISSUE THREAD

**Issue by steebchen** [Daplie/letsencrypt-express#31]
When I run letsencrypt-express with `testing()` all seems working. Now I want to have a valid certificate so that the browser doesn't show the "Your connection is not private" error, so I removed the `testing()` and navigated to https://test.video-download.online/, and after it loaded, I only see the following error message:

> This server could not prove that it is test.video-download.online; its security certificate is from localhost.daplie.com.

The console output:
```
ENCRYPT __ALL__ THE DOMAINS!
ENCRYPT __ALL__ THE DOMAINS!
ENCRYPT __ALL__ THE DOMAINS!
approveRegistration called. hostname: test.video-download.online
[DEBUG le/lib/core.js] registeryAsync err
Error: [Error] letiny-core: not 200 ok
    at bodyToError (/home/downloadserver/node_modules/letiny-core/lib/get-certificate.js:81:15)
    at /home/downloadserver/node_modules/letiny-core/lib/get-certificate.js:265:20
    at Request._callback (/home/downloadserver/node_modules/letiny-core/lib/acme-client.js:102:7)
    at Request.self.callback (/home/downloadserver/node_modules/letiny-core/node_modules/request/request.js:199:22)
    at emitTwo (events.js:100:13)
    at Request.emit (events.js:185:7)
    at Request.<anonymous> (/home/downloadserver/node_modules/letiny-core/node_modules/request/request.js:1036:10)
    at emitOne (events.js:95:20)
    at Request.emit (events.js:182:7)
    at IncomingMessage.<anonymous> (/home/downloadserver/node_modules/letiny-core/node_modules/request/request.js:963:12)
    at emitNone (events.js:85:20)
    at IncomingMessage.emit (events.js:179:7)
    at endReadableNT (_stream_readable.js:913:12)
    at _combinedTickCallback (node.js:383:13)
    at process._tickDomainCallback (node.js:431:11)
```

My server code is as follows:

	var app = express();

	// some routes

	var lexApp = lex.create({
		onRequest: app,
		approveRegistration: function (hostname, cb) {
			console.log('approveRegistration called. hostname:', hostname);
			cb(null, {
				domains: [hostname],
				email: 'contact@luca-steeb.com',
				agreeTos: true
			});
		}
	});

	lexApp.listen([80], [443, 5001], function () {
		console.log("ENCRYPT __ALL__ THE DOMAINS!");
	});

Sometimes, an other error is occurring. I don't know when this happens, but currently it happened when navigating to test.video-download.online a second time.

```
ENCRYPT __ALL__ THE DOMAINS!
ENCRYPT __ALL__ THE DOMAINS!
ENCRYPT __ALL__ THE DOMAINS!
approveRegistration called. hostname: test.video-download.online
[DEBUG le/lib/core.js] registeryAsync err
TypeError: must start with number, buffer, array or string
    at fromObject (buffer.js:140:11)
    at new Buffer (buffer.js:62:10)
    at b64ToBinstr (/home/downloadserver/node_modules/letiny-core/lib/letsencrypt-forge-extra.js:16:10)
    at toForgePrivateKey (/home/downloadserver/node_modules/letiny-core/lib/letsencrypt-forge-extra.js:45:5)
    at Object.privateJwkToPems (/home/downloadserver/node_modules/letiny-core/lib/letsencrypt-forge-extra.js:91:12)
    at Object.tryCatcher (/home/downloadserver/node_modules/bluebird/js/release/util.js:16:23)
    at Object.ret [as privateJwkToPemsAsync] (eval at <anonymous> (/home/downloadserver/node_modules/bluebird/js/release/promisify.js:184:12), <anonymous>:13:39)
    at /home/downloadserver/node_modules/letsencrypt/lib/accounts.js:109:21
    at tryCatcher (/home/downloadserver/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/home/downloadserver/node_modules/bluebird/js/release/promise.js:503:31)
    at Promise._settlePromise (/home/downloadserver/node_modules/bluebird/js/release/promise.js:560:18)
    at Promise._settlePromise0 (/home/downloadserver/node_modules/bluebird/js/release/promise.js:605:10)
    at Promise._settlePromises (/home/downloadserver/node_modules/bluebird/js/release/promise.js:684:18)
    at Promise._fulfill (/home/downloadserver/node_modules/bluebird/js/release/promise.js:629:18)
    at PromiseArray._resolve (/home/downloadserver/node_modules/bluebird/js/release/promise_array.js:125:19)
    at PromiseArray._promiseFulfilled (/home/downloadserver/node_modules/bluebird/js/release/promise_array.js:143:14)
```

Versions:
letsencrypt@1.4.3
letsencrypt-express@1.1.2

**Comment by coolaj86** [comment]
When you switch from testing you need to remove the test files: `rm -rf letsencrypt/etc`

**Comment by steebchen** [comment]
Thanks but now I am receiving this message with the same code:
```
Master-0 TypeError: Cannot set property 'connection' of undefined
Master-0     at ServerResponse.OutgoingMessage.setHeader (_http_outgoing.js:355:26)
Master-0     at ServerResponse.res.setHeader (/home/downloadserver/node_modules/connect/lib/patch.js:134:22)
Master-0     at ServerResponse.res.set.res.header (/home/downloadserver/node_modules/express/lib/response.js:595:10)
Master-0     at Object.handle (/home/downloadserver/master.js:129:8)
Master-0     at next (/home/downloadserver/node_modules/connect/lib/proto.js:174:15)
Master-0     at Object.expressInit [as handle] (/home/downloadserver/node_modules/express/lib/middleware.js:30:5)
Master-0     at next (/home/downloadserver/node_modules/connect/lib/proto.js:174:15)
Master-0     at Object.query [as handle] (/home/downloadserver/node_modules/connect/lib/middleware/query.js:43:5)
Master-0     at next (/home/downloadserver/node_modules/connect/lib/proto.js:174:15)
Master-0     at Function.app.handle (/home/downloadserver/node_modules/connect/lib/proto.js:182:3)
Master-0     at app (/home/downloadserver/node_modules/connect/lib/connect.js:67:37)
Master-0     at Server.httpAcmeResponder (/home/downloadserver/node_modules/letsencrypt-express/lib/standalone.js:17:7)
Master-0     at emitTwo (events.js:100:13)
Master-0     at Server.emit (events.js:185:7)
Master-0     at IncomingMessage.g (events.js:273:16)
Master-0     at emitNone (events.js:80:13)
```

**Comment by steebchen** [comment]
I have delete all data and took the example files, edited some things and it's working now. Thanks.
