### ISSUE TITLE
Possible for multi domain using vhost?

### ISSUE THREAD

**Issue by mannyvergel** [Daplie/letsencrypt-express#34]
Hi! I'm using vhost to have one server host multiple domains. Is it possible to use letsencrypt-express to automatically my domains? What happens currently is the first domain I visit is successfully encrypted, but the succeeding fails.

```
[2016-04-06 14:01:21.163] [INFO] console - [2016-04-06 14:01:21.163] [WARN] console - [LE /lib/core.js] retrieve from domainKeyPath NOT IMPLEMENTED (please file an issue to remind me about this)
[2016-04-06 14:01:23.867] [INFO] console - [2016-04-06 14:01:23.867] [ERROR] console - [DEBUG le/lib/core.js] registeryAsync err
[2016-04-06 14:01:23.867] [INFO] console - [2016-04-06 14:01:23.867] [ERROR] console - Error: The CA was unable to validate the file you provisioned. 
 - https://acme-v01.api.letsencrypt.org/acme/challenge/c5X2vqDSgRYkIZhOJsv2TyXNwbtL-E5aP2VfCaSE1ZI/42907515 [invalid]
   Invalid response from http://www.hashtagcircle.com/.well-known/acme-challenge/NmqPy-IGs9qQPQacYN0nNCdmqRcufJLrZ_Nf_jUUQCs [104.199.164.207]: 404
 - https://acme-v01.api.letsencrypt.org/acme/challenge/c5X2vqDSgRYkIZhOJsv2TyXNwbtL-E5aP2VfCaSE1ZI/42907516 [pending]
 - https://acme-v01.api.letsencrypt.org/acme/challenge/c5X2vqDSgRYkIZhOJsv2TyXNwbtL-E5aP2VfCaSE1ZI/42907517 [pending]
    at handleErr (/home/manny/sitetistry/node_modules/letiny-core/lib/get-certificate.js:372:17)
    at ensureValidation (/home/manny/sitetistry/node_modules/letiny-core/lib/get-certificate.js:245:16)
    at Request._callback (/home/manny/sitetistry/node_modules/letiny-core/lib/get-certificate.js:227:13)
    at Request.self.callback (/home/manny/sitetistry/node_modules/letiny-core/node_modules/request/request.js:200:22)
    at emitTwo (events.js:87:13)
    at Request.emit (events.js:172:7)
    at Request.<anonymous> (/home/manny/sitetistry/node_modules/letiny-core/node_modules/request/request.js:1041:10)
    at emitOne (events.js:82:20)
    at Request.emit (events.js:169:7)
    at IncomingMessage.<anonymous> (/home/manny/sitetistry/node_modules/letiny-core/node_modules/request/request.js:968:12)
    at emitNone (events.js:72:20)
    at IncomingMessage.emit (events.js:166:7)
    at endReadableNT (_stream_readable.js:913:12)
    at nextTickCallbackWith2Args (node.js:442:9)
    at process._tickDomainCallback (node.js:397:17)

```

**Comment by coolaj86** [comment]
I use it for multiple domains.

```
dig www.hashtagcircle.com
dig @8.8.8.8 www.hashtagcircle.com
```

make sure you get the answers you're expecting.

**Comment by mannyvergel** [comment]
You're right. Sorry about that. My acme responder has conflicted with another middleware I use. Thanks!
