### ISSUE TITLE
tls-sni-01 not working

### ISSUE THREAD

**Issue by alexlamsl** [Daplie/letsencrypt-express#42]
I have successfully used `letsencrypt-express` with raw HTTP+HTTPS setup. (Presumably the challenge was done with `http-01`.)

To test the scenario without HTTP access, I have replicated everything except for opening port 80 at the firewall. Account creation went successfully, then I get the follow error:
```
[letsencrypt/lib/core.js] get certificate
[LEX] write file <domain> /tmp/acme-challenge
challenge: zeY6qxTlyl-mdbj7iH78YsWF0zVhfUvl5jgJRDL3iCs
response: zeY6qxTlyl-mdbj7iH78YsWF0zVhfUvl5jgJRDL3iCs.Da1o3SG0jr69MY4CJIhbNItcDmuZdCYxNilg6FNkcI0
[LEX] mkdirp /tmp/acme-challenge
[LEX] write file <domain> /tmp/acme-challenge
challenge: vFIE4HuxVhJ336P1gW_F3LoGoZ5XFo64pF9jhZesxDM
response: vFIE4HuxVhJ336P1gW_F3LoGoZ5XFo64pF9jhZesxDM.9DXrw7Tt3RxxqGGpA381fSErHeSchqsBIWgUXEnFFDs
[LEX] removeChallenge /tmp/acme-challenge/vFIE4HuxVhJ336P1gW_F3LoGoZ5XFo64pF9jhZesxDM <domain> vFIE4HuxVhJ336P1gW_F3LoGoZ5XFo64pF9jhZesxDM
The CA was unable to validate the file you provisioned.
 - https://acme-staging.api.letsencrypt.org/acme/challenge/78yLyqmWTxozm4gJUoMP6wYVZUaU7cWsplcjMhEevVc/5580140 [pending]
 - https://acme-staging.api.letsencrypt.org/acme/challenge/78yLyqmWTxozm4gJUoMP6wYVZUaU7cWsplcjMhEevVc/5580141 [invalid]
   Could not connect to http://<domain>/.well-known/acme-challenge/vFIE4HuxVhJ336P1gW_F3LoGoZ5XFo64pF9jhZesxDM
 - https://acme-staging.api.letsencrypt.org/acme/challenge/78yLyqmWTxozm4gJUoMP6wYVZUaU7cWsplcjMhEevVc/5580142 [pending] null { identifier: { type: 'dns', value: '<domain>' },
  status: 'invalid',
  expires: '2016-05-14T19:35:45Z',
  challenges:
   [ { type: 'tls-sni-01',
       status: 'pending',
       uri: 'https://acme-staging.api.letsencrypt.org/acme/challenge/78yLyqmWTxozm4gJUoMP6wYVZUaU7cWsplcjMhEevVc/5580140',
       token: 'E2IOaLIOlKuG0DwhzQ5zKXUhrG-09epIgBU0S1qnBiU' },
     { type: 'http-01',
       status: 'invalid',
       error: [Object],
       uri: 'https://acme-staging.api.letsencrypt.org/acme/challenge/78yLyqmWTxozm4gJUoMP6wYVZUaU7cWsplcjMhEevVc/5580141',
       token: 'vFIE4HuxVhJ336P1gW_F3LoGoZ5XFo64pF9jhZesxDM',
       keyAuthorization: 'vFIE4HuxVhJ336P1gW_F3LoGoZ5XFo64pF9jhZesxDM.9DXrw7Tt3RxxqGGpA381fSErHeSchqsBIWgUXEnFFDs',
       validationRecord: [Object] },
     { type: 'dns-01',
       status: 'pending',
       uri: 'https://acme-staging.api.letsencrypt.org/acme/challenge/78yLyqmWTxozm4gJUoMP6wYVZUaU7cWsplcjMhEevVc/5580142',
       token: 'U0nfIi2_eFpZO7CwveOt7n9xkdgp1-k_KNeCqbz1B68' } ],
  combinations: [ [ 2 ], [ 1 ], [ 0 ] ] }
[DEBUG le/lib/core.js] registeryAsync err
Error: The CA was unable to validate the file you provisioned.
 - https://acme-staging.api.letsencrypt.org/acme/challenge/78yLyqmWTxozm4gJUoMP6wYVZUaU7cWsplcjMhEevVc/5580140 [pending]
 - https://acme-staging.api.letsencrypt.org/acme/challenge/78yLyqmWTxozm4gJUoMP6wYVZUaU7cWsplcjMhEevVc/5580141 [invalid]
   Could not connect to http://<domain>/.well-known/acme-challenge/vFIE4HuxVhJ336P1gW_F3LoGoZ5XFo64pF9jhZesxDM
 - https://acme-staging.api.letsencrypt.org/acme/challenge/78yLyqmWTxozm4gJUoMP6wYVZUaU7cWsplcjMhEevVc/5580142 [pending]
    at handleErr (node_modules/letsencrypt-express/node_modules/letsencrypt/node_modules/letiny-core/lib/get-certificate.js:372:17)
    at ensureValidation (node_modules/letsencrypt-express/node_modules/letsencrypt/node_modules/letiny-core/lib/get-certificate.js:245:16)
    at Request._callback (node_modules/letsencrypt-express/node_modules/letsencrypt/node_modules/letiny-core/lib/get-certificate.js:227:13)
    at Request.self.callback (node_modules/letsencrypt-express/node_modules/letsencrypt/node_modules/request/request.js:200:22)
    at emitTwo (events.js:87:13)
    at Request.emit (events.js:172:7)
    at Request.<anonymous> (node_modules/letsencrypt-express/node_modules/letsencrypt/node_modules/request/request.js:1067:10)
    at emitOne (events.js:82:20)
    at Request.emit (events.js:169:7)
    at IncomingMessage.<anonymous> (node_modules/letsencrypt-express/node_modules/letsencrypt/node_modules/request/request.js:988:12)
    at emitNone (events.js:72:20)
    at IncomingMessage.emit (events.js:166:7)
    at endReadableNT (_stream_readable.js:913:12)
    at nextTickCallbackWith2Args (node.js:442:9)
    at process._tickCallback (node.js:356:17)
[LEX] '<domain>' register completed Error: The CA was unable to validate the file you provisioned.
 - https://acme-staging.api.letsencrypt.org/acme/challenge/78yLyqmWTxozm4gJUoMP6wYVZUaU7cWsplcjMhEevVc/5580140 [pending]
 - https://acme-staging.api.letsencrypt.org/acme/challenge/78yLyqmWTxozm4gJUoMP6wYVZUaU7cWsplcjMhEevVc/5580141 [invalid]
   Could not connect to http://<domain>/.well-known/acme-challenge/vFIE4HuxVhJ336P1gW_F3LoGoZ5XFo64pF9jhZesxDM
 - https://acme-staging.api.letsencrypt.org/acme/challenge/78yLyqmWTxozm4gJUoMP6wYVZUaU7cWsplcjMhEevVc/5580142 [pending]
    at handleErr (node_modules/letsencrypt-express/node_modules/letsencrypt/node_modules/letiny-core/lib/get-certificate.js:372:17)
    at ensureValidation (node_modules/letsencrypt-express/node_modules/letsencrypt/node_modules/letiny-core/lib/get-certificate.js:245:16)
    at Request._callback (node_modules/letsencrypt-express/node_modules/letsencrypt/node_modules/letiny-core/lib/get-certificate.js:227:13)
    at Request.self.callback (node_modules/letsencrypt-express/node_modules/letsencrypt/node_modules/request/request.js:200:22)
    at emitTwo (events.js:87:13)
    at Request.emit (events.js:172:7)
    at Request.<anonymous> (node_modules/letsencrypt-express/node_modules/letsencrypt/node_modules/request/request.js:1067:10)
    at emitOne (events.js:82:20)
    at Request.emit (events.js:169:7)
    at IncomingMessage.<anonymous> (node_modules/letsencrypt-express/node_modules/letsencrypt/node_modules/request/request.js:988:12)
    at emitNone (events.js:72:20)
    at IncomingMessage.emit (events.js:166:7)
    at endReadableNT (_stream_readable.js:913:12)
    at nextTickCallbackWith2Args (node.js:442:9)
    at process._tickCallback (node.js:356:17) undefined
cert is NOT looking good
[LEX] removeChallenge /tmp/acme-challenge/zeY6qxTlyl-mdbj7iH78YsWF0zVhfUvl5jgJRDL3iCs <domain> zeY6qxTlyl-mdbj7iH78YsWF0zVhfUvl5jgJRDL3iCs
The CA was unable to validate the file you provisioned.
 - https://acme-staging.api.letsencrypt.org/acme/challenge/oCuiDupCmdwOjyEgITYiCSu6ki5QwrP9fVXgAfiaRrY/5580137 [pending]
 - https://acme-staging.api.letsencrypt.org/acme/challenge/oCuiDupCmdwOjyEgITYiCSu6ki5QwrP9fVXgAfiaRrY/5580138 [pending]
 - https://acme-staging.api.letsencrypt.org/acme/challenge/oCuiDupCmdwOjyEgITYiCSu6ki5QwrP9fVXgAfiaRrY/5580139 [invalid]
   Could not connect to http://<domain>/.well-known/acme-challenge/zeY6qxTlyl-mdbj7iH78YsWF0zVhfUvl5jgJRDL3iCs null { identifier: { type: 'dns', value: '<domain>' },
  status: 'invalid',
  expires: '2016-05-14T19:35:45Z',
  challenges:
   [ { type: 'tls-sni-01',
       status: 'pending',
       uri: 'https://acme-staging.api.letsencrypt.org/acme/challenge/oCuiDupCmdwOjyEgITYiCSu6ki5QwrP9fVXgAfiaRrY/5580137',
       token: '6xRU-yGZu7WyurTa_woxgocEtAJsM-X1Eot6xwTrqIo' },
     { type: 'dns-01',
       status: 'pending',
       uri: 'https://acme-staging.api.letsencrypt.org/acme/challenge/oCuiDupCmdwOjyEgITYiCSu6ki5QwrP9fVXgAfiaRrY/5580138',
       token: 'ucVLTJvTGLQvVvkpiVvV60oM3pBeB3tKamb3rKsuYQw' },
     { type: 'http-01',
       status: 'invalid',
       error: [Object],
       uri: 'https://acme-staging.api.letsencrypt.org/acme/challenge/oCuiDupCmdwOjyEgITYiCSu6ki5QwrP9fVXgAfiaRrY/5580139',
       token: 'zeY6qxTlyl-mdbj7iH78YsWF0zVhfUvl5jgJRDL3iCs',
       keyAuthorization: 'zeY6qxTlyl-mdbj7iH78YsWF0zVhfUvl5jgJRDL3iCs.Da1o3SG0jr69MY4CJIhbNItcDmuZdCYxNilg6FNkcI0',
       validationRecord: [Object] } ],
  combinations: [ [ 1 ], [ 2 ], [ 0 ] ] }
[DEBUG le/lib/core.js] registeryAsync err
Error: The CA was unable to validate the file you provisioned.
 - https://acme-staging.api.letsencrypt.org/acme/challenge/oCuiDupCmdwOjyEgITYiCSu6ki5QwrP9fVXgAfiaRrY/5580137 [pending]
 - https://acme-staging.api.letsencrypt.org/acme/challenge/oCuiDupCmdwOjyEgITYiCSu6ki5QwrP9fVXgAfiaRrY/5580138 [pending]
 - https://acme-staging.api.letsencrypt.org/acme/challenge/oCuiDupCmdwOjyEgITYiCSu6ki5QwrP9fVXgAfiaRrY/5580139 [invalid]
   Could not connect to http://<domain>/.well-known/acme-challenge/zeY6qxTlyl-mdbj7iH78YsWF0zVhfUvl5jgJRDL3iCs
    at handleErr (node_modules/letsencrypt-express/node_modules/letsencrypt/node_modules/letiny-core/lib/get-certificate.js:372:17)
    at ensureValidation (node_modules/letsencrypt-express/node_modules/letsencrypt/node_modules/letiny-core/lib/get-certificate.js:245:16)
    at Request._callback (node_modules/letsencrypt-express/node_modules/letsencrypt/node_modules/letiny-core/lib/get-certificate.js:227:13)
    at Request.self.callback (node_modules/letsencrypt-express/node_modules/letsencrypt/node_modules/request/request.js:200:22)
    at emitTwo (events.js:87:13)
    at Request.emit (events.js:172:7)
    at Request.<anonymous> (node_modules/letsencrypt-express/node_modules/letsencrypt/node_modules/request/request.js:1067:10)
    at emitOne (events.js:82:20)
    at Request.emit (events.js:169:7)
    at IncomingMessage.<anonymous> (node_modules/letsencrypt-express/node_modules/letsencrypt/node_modules/request/request.js:988:12)
    at emitNone (events.js:72:20)
    at IncomingMessage.emit (events.js:166:7)
    at endReadableNT (_stream_readable.js:913:12)
    at nextTickCallbackWith2Args (node.js:442:9)
    at process._tickCallback (node.js:356:17)
[LEX] '<domain>' register completed Error: The CA was unable to validate the file you provisioned.
 - https://acme-staging.api.letsencrypt.org/acme/challenge/oCuiDupCmdwOjyEgITYiCSu6ki5QwrP9fVXgAfiaRrY/5580137 [pending]
 - https://acme-staging.api.letsencrypt.org/acme/challenge/oCuiDupCmdwOjyEgITYiCSu6ki5QwrP9fVXgAfiaRrY/5580138 [pending]
 - https://acme-staging.api.letsencrypt.org/acme/challenge/oCuiDupCmdwOjyEgITYiCSu6ki5QwrP9fVXgAfiaRrY/5580139 [invalid]
   Could not connect to http://<domain>/.well-known/acme-challenge/zeY6qxTlyl-mdbj7iH78YsWF0zVhfUvl5jgJRDL3iCs
    at handleErr (node_modules/letsencrypt-express/node_modules/letsencrypt/node_modules/letiny-core/lib/get-certificate.js:372:17)
    at ensureValidation (node_modules/letsencrypt-express/node_modules/letsencrypt/node_modules/letiny-core/lib/get-certificate.js:245:16)
    at Request._callback (node_modules/letsencrypt-express/node_modules/letsencrypt/node_modules/letiny-core/lib/get-certificate.js:227:13)
    at Request.self.callback (node_modules/letsencrypt-express/node_modules/letsencrypt/node_modules/request/request.js:200:22)
    at emitTwo (events.js:87:13)
    at Request.emit (events.js:172:7)
    at Request.<anonymous> (node_modules/letsencrypt-express/node_modules/letsencrypt/node_modules/request/request.js:1067:10)
    at emitOne (events.js:82:20)
    at Request.emit (events.js:169:7)
    at IncomingMessage.<anonymous> (node_modules/letsencrypt-express/node_modules/letsencrypt/node_modules/request/request.js:988:12)
    at emitNone (events.js:72:20)
    at IncomingMessage.emit (events.js:166:7)
    at endReadableNT (_stream_readable.js:913:12)
    at nextTickCallbackWith2Args (node.js:442:9)
    at process._tickCallback (node.js:356:17) undefined
cert is NOT looking good
[LEX] certs for '<domain>' recently failed and are still in cool down
[LEX] certs for '<domain>' recently failed and are still in cool down
```

**Comment by alexlamsl** [comment]
Reading through [the docs](https://github.com/ietf-wg-acme/acme/blob/master/draft-ietf-acme-acme.md#tls-with-server-name-indication-tls-sni) it seems that Let's Encrypt should try and probe my server via SNI using `x.y.token.acme.invalid`, but logging all the `SNICallback`s I don't see any of that in there...

**Comment by coolaj86** [comment]
Did you figure this out?

I don't understand exactly the situation you're describing, but the common errors it sounds like you might be having are if the dns resolution isn't valid to the ip of the server that you're trying to certify and if the firewall isn't allowing all of ports 80 (plain), 443 (tls), and 5001 (tls).

I'm closing this for now since no one else has reported as similar issue and I don't think your issue is actually related to any bug in letsencrypt-express, but feel free to continue the discussion.

**Comment by alexlamsl** [comment]
@coolaj86 yeah it's not a bug - `letsencrypt-express` only supports validation via `http-01`, so basically if a server only have access to port 443 but not 80 then this module can't do much to help.

**Comment by coolaj86** [comment]
Does what you want to do work in the official python client with the production boulder server?

If it works there and it doesn't work here, then it is a bug.

**Comment by alexlamsl** [comment]
`tls-sni-01` does work and is supported by the official client, yes.

Judging by their discussions they will move on to `tls-sni-02` in the near future as well...

**Comment by coolaj86** [comment]
FYI: In version 2.x http-01, tls-sni-01, and dns-01 are all now handled by the `le-challenge-*` plugins (search npm for `le-challenge-`).

Everything has been broken down into much smaller code chunks so that it's easier to grok and build upon.
