### ISSUE TITLE
"retrieve from domainKeyPath NOT IMPLEMENTED" (console output asks me to create this issue)

### ISSUE THREAD

**Issue by RobertWarrenGilmore** [Daplie/letsencrypt-express#43]
```
[DEBUG le/lib/core.js] registeryAsync err
TypeError: must start with number, buffer, array or string
    at fromObject (buffer.js:139:11)
    at new Buffer (buffer.js:58:10)
    at b64ToBinstr (/home/robert/projects/pgSandbox/node_modules/letiny-core/lib/letsencrypt-forge-extra.js:16:10)
    at toForgePrivateKey (/home/robert/projects/pgSandbox/node_modules/letiny-core/lib/letsencrypt-forge-extra.js:45:5)
    at Object.privateJwkToPems (/home/robert/projects/pgSandbox/node_modules/letiny-core/lib/letsencrypt-forge-extra.js:91:12)
    at Object.tryCatcher (/home/robert/projects/pgSandbox/node_modules/bluebird/js/release/util.js:11:23)
    at Object.ret [as privateJwkToPemsAsync] (eval at <anonymous> (/home/robert/projects/pgSandbox/node_modules/bluebird/js/release/promisify.js:184:12), <anonymous>:13:39)
    at /home/robert/projects/pgSandbox/node_modules/letsencrypt/lib/accounts.js:109:21
    at tryCatcher (/home/robert/projects/pgSandbox/node_modules/bluebird/js/release/util.js:11:23)
    at Promise._settlePromiseFromHandler (/home/robert/projects/pgSandbox/node_modules/bluebird/js/release/promise.js:489:31)
    at Promise._settlePromise (/home/robert/projects/pgSandbox/node_modules/bluebird/js/release/promise.js:546:18)
    at Promise._settlePromise0 (/home/robert/projects/pgSandbox/node_modules/bluebird/js/release/promise.js:591:10)
    at Promise._settlePromises (/home/robert/projects/pgSandbox/node_modules/bluebird/js/release/promise.js:674:18)
    at Promise._fulfill (/home/robert/projects/pgSandbox/node_modules/bluebird/js/release/promise.js:615:18)
    at PromiseArray._resolve (/home/robert/projects/pgSandbox/node_modules/bluebird/js/release/promise_array.js:125:19)
    at PromiseArray._promiseFulfilled (/home/robert/projects/pgSandbox/node_modules/bluebird/js/release/promise_array.js:143:14)
    at Promise._settlePromise (/home/robert/projects/pgSandbox/node_modules/bluebird/js/release/promise.js:551:26)
    at Promise._settlePromise0 (/home/robert/projects/pgSandbox/node_modules/bluebird/js/release/promise.js:591:10)
    at Promise._settlePromises (/home/robert/projects/pgSandbox/node_modules/bluebird/js/release/promise.js:674:18)
    at Promise._fulfill (/home/robert/projects/pgSandbox/node_modules/bluebird/js/release/promise.js:615:18)
    at Promise._resolveCallback (/home/robert/projects/pgSandbox/node_modules/bluebird/js/release/promise.js:416:57)
    at Promise._settlePromiseFromHandler (/home/robert/projects/pgSandbox/node_modules/bluebird/js/release/promise.js:502:17)
[LE /lib/core.js] retrieve from domainKeyPath NOT IMPLEMENTED (please file an issue to remind me about this)
```

:laughing:

Maybe next time the code could call the GitHub API to create the issue.

**Comment by coolaj86** [comment]
https://github.com/Daplie/letsencrypt-express/issues/18
