### ISSUE TITLE
Cannot get hapi working

### ISSUE THREAD

**Issue by AdriVanHoudt** [Daplie/letsencrypt-express#55]
I tried the examples but I keep getting the localhost.daplie.com cert.

Is it possible this won't work when testing locally on 0.0.0.0? Even with .testing()
If so how do I test this before using in a staging/production environment?
In those envs the node server still runs on host 0.0.0.0 so not sure what is up.

approveRegistration and handleRenewFailure are never called
I only see `[LEX] creating sniCallback` and that's it

**Comment by AdriVanHoudt** [comment]
ok got a bit further and testing on a Google cloud compute engine and getting this:
```js
  [LEX] testing mode turned on
 [LEX] default server: https://acme-staging.api.letsencrypt.org/directory
 ###################################################
 #                                                 #
 #     Open up a browser and visit this server     #
 #     at its domain name.                         #
 #                                                 #
 #                                 ENJOY!          #
 #                                                 #
 ###################################################
 Note: testing certs will be installed because .testing() was called.
       remove .testing() to get live certs.
 [LEX] automatic registration handling turned on for testing.
 [LEX] creating sniCallback {
   "configDir": "/root/letsencrypt/etc",
   "debug": true,
   "webrootPath": "/tmp/acme-challenge",
   "privkeyPath": "/root/letsencrypt/etc/live/:hostname/privkey.pem",
   "fullchainPath": "/root/letsencrypt/etc/live/:hostname/fullchain.pem",
   "certPath": "/root/letsencrypt/etc/live/:hostname/cert.pem",
   "chainPath": "/root/letsencrypt/etc/live/:hostname/chain.pem",
   "server": "https://acme-staging.api.letsencrypt.org/directory",
   "letsencrypt": {
     "backend": {}
   }
 }
 [LEX] no certs loaded for '[EXTERNAL IP OF CLOUD VM]'
 [LE] fetch
 [letsencrypt/lib/common.js] fetchFromDisk
 Error: ENOENT: no such file or directory, open '/root/letsencrypt/etc/live/[EXTERNAL IP OF CLOUD VM]/privkey.pem'
     at Error (native)
 [LEX] fetch from disk result '[EXTERNAL IP OF CLOUD VM]':
 null
 [LEX] '[EXTERNAL IP OF CLOUD VM]' is not registered, requesting approval
 hostname [EXTERNAL IP OF CLOUD VM]
 [LEX] '[EXTERNAL IP OF CLOUD VM]' registration approved, attempting register
 cert is NOT looking good
 [LEX] certs for '[EXTERNAL IP OF CLOUD VM]' recently failed and are still in cool down
 [LEX] certs for '[EXTERNAL IP OF CLOUD VM]' recently failed and are still in cool down
 [LEX] no certs loaded for '[DOMAIN]'
 [LE] fetch
 [letsencrypt/lib/common.js] fetchFromDisk
 Error: ENOENT: no such file or directory, open '/root/letsencrypt/etc/live/[DOMAIN]/privkey.pem'
     at Error (native)
 [LEX] fetch from disk result '[DOMAIN]':
 null
 [LEX] '[DOMAIN]' is not registered, requesting approval
 hostname [DOMAIN]
 [LEX] '[DOMAIN]' registration approved, attempting register
 [LE] register
 [LE DEBUG] fetch domains { debug: true,
   domains: [ '[DOMAIN]' ],
   email: 'adri@salesflare.com',
   agreeTos: true,
   configDir: '/root/letsencrypt/etc',
   approveRegistration: [Function],
   handleRenewFailure: [Function],
   getChallenge: [Function: getChallenge],
   webrootPath: '/tmp/acme-challenge',
   privkeyPath: '/root/letsencrypt/etc/live/[DOMAIN]/privkey.pem',
   fullchainPath: '/root/letsencrypt/etc/live/[DOMAIN]/fullchain.pem',
   certPath: '/root/letsencrypt/etc/live/[DOMAIN]/cert.pem',
   chainPath: '/root/letsencrypt/etc/live/[DOMAIN]/chain.pem',
   server: 'https://acme-staging.api.letsencrypt.org/directory',
   setChallenge: [Function: setChallenge],
   removeChallenge: [Function: removeChallenge],
   letsencrypt:
    { backend:
       { registerAsync: [Function],
         fetchAsync: [Function],
         configureAsync: [Function],
         getConfigAsync: [Function],
         getConfigsAsync: [Function],
         registerAsyncAsync: [Function],
         fetchAsyncAsync: [Function],
         configureAsyncAsync: [Function],
         getConfigAsyncAsync: [Function],
         getConfigsAsyncAsync: [Function] },
      pyToJson: [Function],
      validate: [Function],
      _registerHelper: [Function],
      _fetchHelper: [Function],
      fetch: [Function],
      renew: [Function],
      getConfig: [Function],
      getConfigs: [Function],
      setConfig: [Function],
      register: [Function] },
   lifetime: 7776000000,
   failedWait: 300000,
   renewWithin: 259200000,
   memorizeFor: 86400000,
   httpsOptions:
    { key: <Buffer 2d 2d 2d 2d 2d 42 45 47 49 4e 20 52 53 41 20 50 52 49 56 41 54 45 20 4b 45 59 2d 2d 2d 2d 2d 0a 4d 49 49 45 70 51 49 42 41 41 4b 43 41 51 45 41 6e 65 ... >,
      cert: <Buffer 2d 2d 2d 2d 2d 42 45 47 49 4e 20 43 45 52 54 49 46 49 43 41 54 45 2d 2d 2d 2d 2d 0a 4d 49 49 46 61 6a 43 43 42 46 4b 67 41 77 49 42 41 67 49 51 64 73 ... >,
      SNICallback: [Function: sniCallback],
      NPNProtocols: [ 'http/1.1', 'http/1.0' ] },
   listen: [Function: listen] }
 [LEX] '[DOMAIN]' registration approved, attempting register
 cert is NOT looking good
 2016-06-20 | 13:06:17.361, [log,connection,client,error], data: {}
 [letsencrypt/lib/common.js] fetchFromDisk
 Error: ENOENT: no such file or directory, open '/root/letsencrypt/etc/live/[DOMAIN]/privkey.pem'
     at Error (native)
 [LE] raw fetch certs null
 [NLE]: begin registration
 [LE DEBUG] reg domains [ '[DOMAIN]' ]
 [LE] try email
 [LE] create account
 [LEX] certs for '[DOMAIN]' recently failed and are still in cool down
 [LEX] certs for '[DOMAIN]' recently failed and are still in cool down
 [LE] created account
 ################   privkeyPath   ################
 /root/letsencrypt/etc/live/[DOMAIN]/privkey.pem
 [letsencrypt/lib/common.js] fetchFromDisk
 Error: ENOENT: no such file or directory, open '/root/letsencrypt/etc/live/[DOMAIN]/privkey.pem'
     at Error (native)
 [letsencrypt/lib/core.js] get certificate
 2016-06-20 | 13:06:19.630, [ops], memory: 123Mb, uptime (seconds): 17.703, load: 0.06591796875,0.05029296875,0.04931640625
 [LEX] write file [DOMAIN] /tmp/acme-challenge
 challenge: Lmew6NTD68QkYeK5XGyJSn3VaeA5vJd5njTQL9KyBZ8
 response: Lmew6NTD68QkYeK5XGyJSn3VaeA5vJd5njTQL9KyBZ8.4vTaKo1uu4kp-Si1KjuzGXAsDhtnxjq8PbmtbonYURU
 [LEX] removeChallenge /tmp/acme-challenge/Lmew6NTD68QkYeK5XGyJSn3VaeA5vJd5njTQL9KyBZ8 [DOMAIN] Lmew6NTD68QkYeK5XGyJSn3VaeA5vJd5njTQL9KyBZ8
 The CA was unable to validate the file you provisioned.
  - https://acme-staging.api.letsencrypt.org/acme/challenge/D8W0kYSE_GkVKX5aZ2j8VaQ9m95SnF9AdliuN1rQMeE/8911859 [pending]
  - https://acme-staging.api.letsencrypt.org/acme/challenge/D8W0kYSE_GkVKX5aZ2j8VaQ9m95SnF9AdliuN1rQMeE/8911860 [invalid]
    Could not connect to http://[DOMAIN]/.well-known/acme-challenge/Lmew6NTD68QkYeK5XGyJSn3VaeA5vJd5njTQL9KyBZ8
  - https://acme-staging.api.letsencrypt.org/acme/challenge/D8W0kYSE_GkVKX5aZ2j8VaQ9m95SnF9AdliuN1rQMeE/8911861 [pending] null { identifier: { type: 'dns', value: '[DOMAIN]' },
   status: 'invalid',
   expires: '2016-06-27T13:06:19Z',
   challenges:
    [ { type: 'dns-01',
        status: 'pending',
        uri: 'https://acme-staging.api.letsencrypt.org/acme/challenge/D8W0kYSE_GkVKX5aZ2j8VaQ9m95SnF9AdliuN1rQMeE/8911859',
        token: 'mtIGNzX8jfFaMGIOWyhAGIdGT-bHf4_fru4zTzwDT8M' },
      { type: 'http-01',
        status: 'invalid',
        error: [Object],
        uri: 'https://acme-staging.api.letsencrypt.org/acme/challenge/D8W0kYSE_GkVKX5aZ2j8VaQ9m95SnF9AdliuN1rQMeE/8911860',
        token: 'Lmew6NTD68QkYeK5XGyJSn3VaeA5vJd5njTQL9KyBZ8',
        keyAuthorization: 'Lmew6NTD68QkYeK5XGyJSn3VaeA5vJd5njTQL9KyBZ8.4vTaKo1uu4kp-Si1KjuzGXAsDhtnxjq8PbmtbonYURU',
        validationRecord: [Object] },
      { type: 'tls-sni-01',
        status: 'pending',
        uri: 'https://acme-staging.api.letsencrypt.org/acme/challenge/D8W0kYSE_GkVKX5aZ2j8VaQ9m95SnF9AdliuN1rQMeE/8911861',
        token: '5zqW-5WiXW-hDlQ6ldPc3SF12ivP_j6FNP11XPP_g88' } ],
   combinations: [ [ 2 ], [ 0 ], [ 1 ] ] }
 [DEBUG le/lib/core.js] registeryAsync err
 Error: The CA was unable to validate the file you provisioned.
  - https://acme-staging.api.letsencrypt.org/acme/challenge/D8W0kYSE_GkVKX5aZ2j8VaQ9m95SnF9AdliuN1rQMeE/8911859 [pending]
  - https://acme-staging.api.letsencrypt.org/acme/challenge/D8W0kYSE_GkVKX5aZ2j8VaQ9m95SnF9AdliuN1rQMeE/8911860 [invalid]
    Could not connect to http://[DOMAIN]/.well-known/acme-challenge/Lmew6NTD68QkYeK5XGyJSn3VaeA5vJd5njTQL9KyBZ8
  - https://acme-staging.api.letsencrypt.org/acme/challenge/D8W0kYSE_GkVKX5aZ2j8VaQ9m95SnF9AdliuN1rQMeE/8911861 [pending]
     at handleErr (/home/[PROJECT]/node_modules/letiny-core/lib/get-certificate.js:372:17)
     at ensureValidation (/home/[PROJECT]/node_modules/letiny-core/lib/get-certificate.js:245:16)
     at Request._callback (/home/[PROJECT]/node_modules/letiny-core/lib/get-certificate.js:227:13)
     at Request.self.callback (/home/[PROJECT]/node_modules/request/request.js:200:22)
     at emitTwo (events.js:87:13)
     at Request.emit (events.js:172:7)
     at Request.<anonymous> (/home/[PROJECT]/node_modules/request/request.js:1067:10)
     at emitOne (events.js:82:20)
     at Request.emit (events.js:169:7)
     at IncomingMessage.<anonymous> (/home/[PROJECT]/node_modules/request/request.js:988:12)
     at emitNone (events.js:72:20)
     at IncomingMessage.emit (events.js:166:7)
     at endReadableNT (_stream_readable.js:913:12)
     at instrumented (/home/[PROJECT]/node_modules/opbeat/lib/instrumentation/index.js:113:27)
     at /home/[PROJECT]/node_modules/async-listener/glue.js:188:31
     at nextTickCallbackWith2Args (node.js:442:9)
     at process._tickDomainCallback [as _tickCallback] (node.js:397:17)
 [LEX] '[DOMAIN]' register completed Error: The CA was unable to validate the file you provisioned.
  - https://acme-staging.api.letsencrypt.org/acme/challenge/D8W0kYSE_GkVKX5aZ2j8VaQ9m95SnF9AdliuN1rQMeE/8911859 [pending]
  - https://acme-staging.api.letsencrypt.org/acme/challenge/D8W0kYSE_GkVKX5aZ2j8VaQ9m95SnF9AdliuN1rQMeE/8911860 [invalid]
    Could not connect to http://[DOMAIN]/.well-known/acme-challenge/Lmew6NTD68QkYeK5XGyJSn3VaeA5vJd5njTQL9KyBZ8
  - https://acme-staging.api.letsencrypt.org/acme/challenge/D8W0kYSE_GkVKX5aZ2j8VaQ9m95SnF9AdliuN1rQMeE/8911861 [pending]
     at handleErr (/home/[PROJECT]/node_modules/letiny-core/lib/get-certificate.js:372:17)
     at ensureValidation (/home/[PROJECT]/node_modules/letiny-core/lib/get-certificate.js:245:16)
     at Request._callback (/home/[PROJECT]/node_modules/letiny-core/lib/get-certificate.js:227:13)
     at Request.self.callback (/home/[PROJECT]/node_modules/request/request.js:200:22)
     at emitTwo (events.js:87:13)
     at Request.emit (events.js:172:7)
     at Request.<anonymous> (/home/[PROJECT]/node_modules/request/request.js:1067:10)
     at emitOne (events.js:82:20)
     at Request.emit (events.js:169:7)
     at IncomingMessage.<anonymous> (/home/[PROJECT]/node_modules/request/request.js:988:12)
     at emitNone (events.js:72:20)
     at IncomingMessage.emit (events.js:166:7)
     at endReadableNT (_stream_readable.js:913:12)
     at instrumented (/home/[PROJECT]/node_modules/opbeat/lib/instrumentation/index.js:113:27)
     at /home/[PROJECT]/node_modules/async-listener/glue.js:188:31
     at nextTickCallbackWith2Args (node.js:442:9)
     at process._tickDomainCallback [as _tickCallback] (node.js:397:17) undefined
 cert is NOT looking good
 [LEX] certs for '[DOMAIN]' recently failed and are still in cool down
```

**Comment by wmertens** [comment]
is your server able to write to `/root/letsencrypt/etc/`? If not, that's probably the issue. If so, that seems like a bad idea, running the server with root privileges?

**Comment by coolaj86** [comment]
Agreed, this looks like a linux permissions problem, not a problem with the library.
