### ISSUE TITLE
Error with simple example

### ISSUE THREAD

**Issue by larslue** [Daplie/letsencrypt-express#56]
Hi there,

I am trying to use this package for my express REST API. I use a Docker environment where I expose the ports 80, 443 and 5001 as written in the example.
These are mapped externally to 3001:80 (for HTTP), 3000:443 (for HTTPS) and 5001:5001 (for something I don't know).
Using with HTTP works but using HTTPS on port 3001 gives this error (I exchanged the domain name for privacy purposes):
```bash
2016-07-08T16:39:09.877450651Z > node app.js
2016-07-08T16:39:09.877456628Z 
2016-07-08T16:39:10.656379734Z [LEX] testing mode turned on
2016-07-08T16:39:10.658453068Z [LEX] default server: https://acme-staging.api.letsencrypt.org/directory
2016-07-08T16:39:10.658782354Z 
2016-07-08T16:39:10.658824482Z 
2016-07-08T16:39:10.658917555Z ###################################################
2016-07-08T16:39:10.659015405Z #                                                 #
2016-07-08T16:39:10.659108516Z #     Open up a browser and visit this server     #
2016-07-08T16:39:10.659199412Z #     at its domain name.                         #
2016-07-08T16:39:10.659294377Z #                                                 #
2016-07-08T16:39:10.659396506Z #                                 ENJOY!          #
2016-07-08T16:39:10.659494915Z #                                                 #
2016-07-08T16:39:10.659588615Z ###################################################
2016-07-08T16:39:10.659676944Z 
2016-07-08T16:39:10.659687985Z 
2016-07-08T16:39:10.659771285Z Note: testing certs will be installed because .testing() was called.
2016-07-08T16:39:10.659855382Z       remove .testing() to get live certs.
2016-07-08T16:39:10.659932792Z 
2016-07-08T16:39:10.659943575Z 
2016-07-08T16:39:10.660028599Z [LEX] automatic registration handling turned on for testing.
2016-07-08T16:39:10.660118004Z 
2016-07-08T16:39:10.660135031Z 
2016-07-08T16:39:10.813521159Z [LEX] creating sniCallback {
2016-07-08T16:39:10.813554888Z   "configDir": "/root/letsencrypt/etc",
2016-07-08T16:39:10.813560274Z   "debug": true,
2016-07-08T16:39:10.813564582Z   "webrootPath": "/usr/src/app/acme-challenge",
2016-07-08T16:39:10.813569091Z   "privkeyPath": "/root/letsencrypt/etc/live/:hostname/privkey.pem",
2016-07-08T16:39:10.813573546Z   "fullchainPath": "/root/letsencrypt/etc/live/:hostname/fullchain.pem",
2016-07-08T16:39:10.813578321Z   "certPath": "/root/letsencrypt/etc/live/:hostname/cert.pem",
2016-07-08T16:39:10.813582777Z   "chainPath": "/root/letsencrypt/etc/live/:hostname/chain.pem",
2016-07-08T16:39:10.813587193Z   "server": "https://acme-staging.api.letsencrypt.org/directory",
2016-07-08T16:39:10.813607205Z   "letsencrypt": {
2016-07-08T16:39:10.813611951Z     "backend": {}
2016-07-08T16:39:10.813616760Z   }
2016-07-08T16:39:10.813620879Z }
2016-07-08T16:39:10.879920447Z Listening at http://localhost:80
2016-07-08T16:39:10.880268837Z Listening at https://localhost:443
2016-07-08T16:39:10.880430173Z Listening at https://localhost:5001
2016-07-08T16:39:43.499713746Z [LEX] no certs loaded for '<domain>'
2016-07-08T16:39:43.500049997Z [LE] fetch
2016-07-08T16:39:43.510276857Z [letsencrypt/lib/common.js] fetchFromDisk
2016-07-08T16:39:43.510365975Z Error: ENOENT: no such file or directory, open '/root/letsencrypt/etc/live/<domain>/privkey.pem'
2016-07-08T16:39:43.510378057Z     at Error (native)
2016-07-08T16:39:43.511264739Z [LEX] fetch from disk result '<domain>':
2016-07-08T16:39:43.512527165Z null
2016-07-08T16:39:43.512757432Z [LEX] '<domain>' is not registered, requesting approval
2016-07-08T16:39:43.513350196Z [LEX] '<domain>' registration approved, attempting register
2016-07-08T16:39:43.513587048Z [LE] register
2016-07-08T16:39:43.515449115Z [letsencrypt/lib/common.js] fetchFromDisk
2016-07-08T16:39:43.515526575Z Error: ENOENT: no such file or directory, open '/root/letsencrypt/etc/live/<domain>/privkey.pem'
2016-07-08T16:39:43.515542852Z     at Error (native)
2016-07-08T16:39:43.516651188Z [NLE]: begin registration
2016-07-08T16:39:43.519855740Z [LE DEBUG] reg domains [ '<domain>' ]
2016-07-08T16:39:43.526689282Z [LE] try email
2016-07-08T16:39:43.784133528Z [LE] create account
2016-07-08T16:39:45.524024262Z [LE] created account
2016-07-08T16:39:45.530332138Z ################   privkeyPath   ################
2016-07-08T16:39:45.530436346Z /root/letsencrypt/etc/live/<domain>/privkey.pem
2016-07-08T16:39:45.536293549Z [letsencrypt/lib/common.js] fetchFromDisk
2016-07-08T16:39:45.536315224Z Error: ENOENT: no such file or directory, open '/root/letsencrypt/etc/live/<domain>/privkey.pem'
2016-07-08T16:39:45.536321314Z     at Error (native)
2016-07-08T16:39:45.634881092Z [letsencrypt/lib/core.js] get certificate
2016-07-08T16:39:46.126852674Z [LEX] write file <domain> /usr/src/app/acme-challenge
2016-07-08T16:39:46.126897362Z challenge: w1iLi226_1cJ6CsPkC4oT0jgCdhfauuFAbMBl8CmGgo
2016-07-08T16:39:46.126933321Z response: w1iLi226_1cJ6CsPkC4oT0jgCdhfauuFAbMBl8CmGgo.3hHsOLEfnPOvCv2woBgxeE9i3YQdKGcI93wbHCcbXh0
2016-07-08T16:39:46.127445856Z [LEX] mkdirp /usr/src/app/acme-challenge
2016-07-08T16:39:47.636453653Z [LEX] removeChallenge /usr/src/app/acme-challenge/w1iLi226_1cJ6CsPkC4oT0jgCdhfauuFAbMBl8CmGgo <domain> w1iLi226_1cJ6CsPkC4oT0jgCdhfauuFAbMBl8CmGgo
2016-07-08T16:39:47.652565187Z The CA was unable to validate the file you provisioned. 
2016-07-08T16:39:47.652594338Z  - https://acme-staging.api.letsencrypt.org/acme/challenge/GxzlEWOlYhfCZqPBNqEjTY-kXbAZYFOWkea3p3thffE/9538133 [invalid]
2016-07-08T16:39:47.652600350Z    Could not connect to http://<domain>/.well-known/acme-challenge/w1iLi226_1cJ6CsPkC4oT0jgCdhfauuFAbMBl8CmGgo
2016-07-08T16:39:47.652608457Z  - https://acme-staging.api.letsencrypt.org/acme/challenge/GxzlEWOlYhfCZqPBNqEjTY-kXbAZYFOWkea3p3thffE/9538134 [pending]
2016-07-08T16:39:47.652613746Z  - https://acme-staging.api.letsencrypt.org/acme/challenge/GxzlEWOlYhfCZqPBNqEjTY-kXbAZYFOWkea3p3thffE/9538135 [pending] null { identifier: { type: 'dns', value: '<domain>' },
2016-07-08T16:39:47.652618529Z   status: 'invalid',
2016-07-08T16:39:47.652622985Z   expires: '2016-07-15T16:39:46Z',
2016-07-08T16:39:47.652627724Z   challenges: 
2016-07-08T16:39:47.652631950Z    [ { type: 'http-01',
2016-07-08T16:39:47.652636178Z        status: 'invalid',
2016-07-08T16:39:47.652640364Z        error: [Object],
2016-07-08T16:39:47.652644569Z        uri: 'https://acme-staging.api.letsencrypt.org/acme/challenge/GxzlEWOlYhfCZqPBNqEjTY-kXbAZYFOWkea3p3thffE/9538133',
2016-07-08T16:39:47.652649035Z        token: 'w1iLi226_1cJ6CsPkC4oT0jgCdhfauuFAbMBl8CmGgo',
2016-07-08T16:39:47.652653312Z        keyAuthorization: 'w1iLi226_1cJ6CsPkC4oT0jgCdhfauuFAbMBl8CmGgo.3hHsOLEfnPOvCv2woBgxeE9i3YQdKGcI93wbHCcbXh0',
2016-07-08T16:39:47.652657750Z        validationRecord: [Object] },
2016-07-08T16:39:47.652661901Z      { type: 'dns-01',
2016-07-08T16:39:47.652665945Z        status: 'pending',
2016-07-08T16:39:47.652670063Z        uri: 'https://acme-staging.api.letsencrypt.org/acme/challenge/GxzlEWOlYhfCZqPBNqEjTY-kXbAZYFOWkea3p3thffE/9538134',
2016-07-08T16:39:47.652674471Z        token: 'pzUw2o4w_leoy-IVkTwVccnf6LgK1Q8oZeTmRFZWzBI' },
2016-07-08T16:39:47.652678691Z      { type: 'tls-sni-01',
2016-07-08T16:39:47.652682759Z        status: 'pending',
2016-07-08T16:39:47.652686826Z        uri: 'https://acme-staging.api.letsencrypt.org/acme/challenge/GxzlEWOlYhfCZqPBNqEjTY-kXbAZYFOWkea3p3thffE/9538135',
2016-07-08T16:39:47.652691315Z        token: 'DL0xGMTTDIrnjM2AJwEqtAJrzOEMvBV0JgeL7AMTe1I' } ],
2016-07-08T16:39:47.652695558Z   combinations: [ [ 2 ], [ 0 ], [ 1 ] ] }
2016-07-08T16:39:47.653672512Z [DEBUG le/lib/core.js] registeryAsync err
2016-07-08T16:39:47.653777977Z Error: The CA was unable to validate the file you provisioned. 
2016-07-08T16:39:47.653790544Z  - https://acme-staging.api.letsencrypt.org/acme/challenge/GxzlEWOlYhfCZqPBNqEjTY-kXbAZYFOWkea3p3thffE/9538133 [invalid]
2016-07-08T16:39:47.653796295Z    Could not connect to http://<domain>/.well-known/acme-challenge/w1iLi226_1cJ6CsPkC4oT0jgCdhfauuFAbMBl8CmGgo
2016-07-08T16:39:47.653811994Z  - https://acme-staging.api.letsencrypt.org/acme/challenge/GxzlEWOlYhfCZqPBNqEjTY-kXbAZYFOWkea3p3thffE/9538134 [pending]
2016-07-08T16:39:47.653816996Z  - https://acme-staging.api.letsencrypt.org/acme/challenge/GxzlEWOlYhfCZqPBNqEjTY-kXbAZYFOWkea3p3thffE/9538135 [pending]
2016-07-08T16:39:47.653821566Z     at handleErr (/usr/src/app/node_modules/letiny-core/lib/get-certificate.js:372:17)
2016-07-08T16:39:47.653825982Z     at ensureValidation (/usr/src/app/node_modules/letiny-core/lib/get-certificate.js:245:16)
2016-07-08T16:39:47.653830386Z     at Request._callback (/usr/src/app/node_modules/letiny-core/lib/get-certificate.js:227:13)
2016-07-08T16:39:47.653834713Z     at Request.self.callback (/usr/src/app/node_modules/request/request.js:200:22)
2016-07-08T16:39:47.653839051Z     at emitTwo (events.js:106:13)
2016-07-08T16:39:47.653843167Z     at Request.emit (events.js:191:7)
2016-07-08T16:39:47.653847315Z     at Request.<anonymous> (/usr/src/app/node_modules/request/request.js:1067:10)
2016-07-08T16:39:47.653853678Z     at emitOne (events.js:101:20)
2016-07-08T16:39:47.653857824Z     at Request.emit (events.js:188:7)
2016-07-08T16:39:47.653862048Z     at IncomingMessage.<anonymous> (/usr/src/app/node_modules/request/request.js:988:12)
2016-07-08T16:39:47.653866696Z     at emitNone (events.js:91:20)
2016-07-08T16:39:47.653870921Z     at IncomingMessage.emit (events.js:185:7)
2016-07-08T16:39:47.653875134Z     at endReadableNT (_stream_readable.js:934:12)
2016-07-08T16:39:47.653879391Z     at _combinedTickCallback (internal/process/next_tick.js:74:11)
2016-07-08T16:39:47.653883722Z     at process._tickCallback (internal/process/next_tick.js:98:9)
2016-07-08T16:39:47.654538838Z [LEX] '<domain>' register completed Error: The CA was unable to validate the file you provisioned. 
2016-07-08T16:39:47.654552120Z  - https://acme-staging.api.letsencrypt.org/acme/challenge/GxzlEWOlYhfCZqPBNqEjTY-kXbAZYFOWkea3p3thffE/9538133 [invalid]
2016-07-08T16:39:47.654557806Z    Could not connect to http://<domain>/.well-known/acme-challenge/w1iLi226_1cJ6CsPkC4oT0jgCdhfauuFAbMBl8CmGgo
2016-07-08T16:39:47.654562400Z  - https://acme-staging.api.letsencrypt.org/acme/challenge/GxzlEWOlYhfCZqPBNqEjTY-kXbAZYFOWkea3p3thffE/9538134 [pending]
2016-07-08T16:39:47.654567057Z  - https://acme-staging.api.letsencrypt.org/acme/challenge/GxzlEWOlYhfCZqPBNqEjTY-kXbAZYFOWkea3p3thffE/9538135 [pending]
2016-07-08T16:39:47.654571630Z     at handleErr (/usr/src/app/node_modules/letiny-core/lib/get-certificate.js:372:17)
2016-07-08T16:39:47.654576020Z     at ensureValidation (/usr/src/app/node_modules/letiny-core/lib/get-certificate.js:245:16)
2016-07-08T16:39:47.654580506Z     at Request._callback (/usr/src/app/node_modules/letiny-core/lib/get-certificate.js:227:13)<domain>
2016-07-08T16:39:47.654584881Z     at Request.self.callback (/usr/src/app/node_modules/request/request.js:200:22)
2016-07-08T16:39:47.654589375Z     at emitTwo (events.js:106:13)
2016-07-08T16:39:47.654599597Z     at Request.emit (events.js:191:7)
2016-07-08T16:39:47.654604294Z     at Request.<anonymous> (/usr/src/app/node_modules/request/request.js:1067:10)
2016-07-08T16:39:47.654608961Z     at emitOne (events.js:101:20)
2016-07-08T16:39:47.654613051Z     at Request.emit (events.js:188:7)
2016-07-08T16:39:47.654617225Z     at IncomingMessage.<anonymous> (/usr/src/app/node_modules/request/request.js:988:12)
2016-07-08T16:39:47.654621752Z     at emitNone (events.js:91:20)
2016-07-08T16:39:47.654625832Z     at IncomingMessage.emit (events.js:185:7)
2016-07-08T16:39:47.654630187Z     at endReadableNT (_stream_readable.js:934:12)
2016-07-08T16:39:47.654636162Z     at _combinedTickCallback (internal/process/next_tick.js:74:11)
2016-07-08T16:39:47.654640556Z     at process._tickCallback (internal/process/next_tick.js:98:9) undefined
2016-07-08T16:39:47.654917043Z cert is NOT looking good
2016-07-08T16:39:47.762370842Z [LEX] certs for '<domain>' recently failed and are still in cool down
2016-07-08T16:39:47.869223055Z [LEX] certs for '<domain>' recently failed and are still in cool down
2016-07-08T16:39:47.951159109Z [LEX]  GET <domain>:3000 /
```

It might be a simple issue but I have absolutely no clue. Thanks!

**Comment by wmertens** [comment]
You need to make sure that letsencrypt.org can access your VM on ports 80 and 443. Apparently, that is not the case.

**Comment by larslue** [comment]
That's true that's not the case. The internal ports are mapped to 3000 and 3001 with Docker. 
Thanks for the help.

**Comment by wmertens** [comment]
…so if you want to make it work, you will need to port forward 80 and 443. You can do that by running `iptables -A PREROUTING -t nat -p tcp --dport 80 -j REDIRECT --to-port 3000; iptables -A PREROUTING -t nat -p tcp --dport 443 -j REDIRECT --to-port 3001` as root.

I guess this can be closed?

**Comment by larslue** [comment]
Yes Thanks a lot for the help!

**Comment by wenduzer** [comment]
Can I get the dockerfile?

**Comment by coolaj86** [comment]
Much better documentation now at
https://git.coolaj86.com/coolaj86/greenlock-express.js
