### ISSUE TITLE
retrieve from domainKeyPath NOT IMPLEMENTED (please file an issue to remind me about this)

### ISSUE THREAD

**Issue by dcsan** [Daplie/letsencrypt-express#58]
I'm getting the error below with a note to remind about the error

retrieve from domainKeyPath NOT IMPLEMENTED (please file an issue to remind me about this

so, here's a reminder :-)

is there any workaround or reason for this? my code seems as simple as can be, straight out of the README.

```
piq-3 debug: Setting up a handler for message_received
piq-3 debug: Setting up a handler for message_received
piq-3 debug: Setting up a handler for message_received
piq-3 debug: Setting up a handler for message_received
piq-3 Listening at http://localhost:80
piq-3 Listening at https://localhost:443
piq-3 Listening at https://localhost:5001
piq-3 [LE /lib/core.js] retrieve from domainKeyPath NOT IMPLEMENTED (please file an issue to remind me about this)
piq-3 [DEBUG le/lib/core.js] registeryAsync err
piq-3 Error: [Error] letiny-core: not 200 ok
piq-3     at bodyToError (/root/www/piq/node_modules/letsencrypt-express/node_modules/letsencrypt/node_modules/letiny-core/lib/get-certificate.js:81:15)
piq-3     at /root/www/piq/node_modules/letsencrypt-express/node_modules/letsencrypt/node_modules/letiny-core/lib/get-certificate.js:265:20
piq-3     at Request._callback (/root/www/piq/node_modules/letsencrypt-express/node_modules/letsencrypt/node_modules/letiny-core/lib/acme-client.js:102:7)
piq-3     at Request.self.callback (/root/www/piq/node_modules/request/request.js:187:22)
piq-3     at emitTwo (events.js:87:13)
piq-3     at Request.emit (events.js:172:7)
piq-3     at Request.<anonymous> (/root/www/piq/node_modules/request/request.js:1044:10)
piq-3     at emitOne (events.js:77:13)
piq-3     at Request.emit (events.js:169:7)
piq-3     at IncomingMessage.<anonymous> (/root/www/piq/node_modules/request/request.js:965:12)
piq-3     at emitNone (events.js:72:20)
piq-3     at IncomingMessage.emit (events.js:166:7)
piq-3     at endReadableNT (_stream_readable.js:913:12)
piq-3     at nextTickCallbackWith2Args (node.js:442:9)
piq-3     at process._tickDomainCallback (node.js:397:17)
piq-3 [DEBUG le/lib/core.js] registeryAsync err
piq-3 Error: [Error] letiny-core: not 200 ok
piq-3     at bodyToError (/root/www/piq/node_modules/letsencrypt-express/node_modules/letsencrypt/node_modules/letiny-core/lib/get-certificate.js:81:15)
piq-3     at /root/www/piq/node_modules/letsencrypt-express/node_modules/letsencrypt/node_modules/letiny-core/lib/get-certificate.js:265:20
piq-3     at Request._callback (/root/www/piq/node_modules/letsencrypt-express/node_modules/letsencrypt/node_modules/letiny-core/lib/acme-client.js:102:7)
piq-3     at Request.self.callback (/root/www/piq/node_modules/request/request.js:187:22)
piq-3     at emitTwo (events.js:87:13)
piq-3     at Request.emit (events.js:172:7)
piq-3     at Request.<anonymous> (/root/www/piq/node_modules/request/request.js:1044:10)
piq-3     at emitOne (events.js:77:13)
piq-3     at Request.emit (events.js:169:7)
piq-3     at IncomingMessage.<anonymous> (/root/www/piq/node_modules/request/request.js:965:12)
piq-3     at emitNone (events.js:72:20)
piq-3     at IncomingMessage.emit (events.js:166:7)
piq-3     at endReadableNT (_stream_readable.js:913:12)
piq-3     at nextTickCallbackWith2Args (node.js:442:9)
piq-3     at process._tickDomainCallback (node.js:397:17)

```

**Comment by dcsan** [comment]
my code looks like this:

```js

"use strict";

var localtunnel = require('localtunnel'),
		express			= require('express'),
		path 				= require('path');

var WebServer = {};

/* Note: using staging server url, remove .testing() for production
Using .testing() will overwrite the debug flag with true */
		// .testing()
var LEX = require('letsencrypt-express');

// Change these two lines!
var DOMAIN = 'piq.FOO.ai';
var EMAIL = 'foo@bar.com';

var lex = LEX.create({
  configDir: require('os').homedir() + '/letsencrypt/etc',
		approveRegistration: function (hostname, approve) { // leave `null` to disable automatic registration
    if (hostname === DOMAIN) { // Or check a database or list of allowed domains
      approve(null, {
        domains: [DOMAIN],
				email: EMAIL,
				agreeTos: true
      });
    }
  }
});



WebServer.init = function(controller, bot, ops) {
	var express = require('express');
	var app = express();

	// app.use(function (req, res) {
	// 	res.send({ success: true });
	// });

	lex.onRequest = app;

	lex.listen([80], [443, 5001], function () {
		var protocol = ('requestCert' in this) ? 'https' : 'http';
		console.log("Listening at " + protocol + '://localhost:' + this.address().port);
	});

	app.get('/ping', function(req, res) {
		res.send("pong");
	});

	// static files
	var pubpath = path.join(__dirname, '../public');
	console.log("public", pubpath);
	app.use(express.static(pubpath));

	controller.createWebhookEndpoints(app, bot, function() {
		console.log('ONLINE!');
	});

};
```

**Comment by dcsan** [comment]
btw I had run the letsencrypt CLI on the target machine and created a cert already. could that have any effect?

**Comment by coolaj86** [comment]
It has nothing to do with the domainKeyPath. See https://github.com/Daplie/letsencrypt-express/issues/18

It may just have been that the let's encrypt servers were down for part of the day yesterday.

`rm -rf letsencrypt` and try again

**Comment by dcsan** [comment]
thanks @coolaj86 I removed the letsencrypt dir as you suggested and rebooted the server, but I get exactly the same error. any other suggestions?

env as below

```
$ node -v
v4.4.3
$ npm -v
2.15.1

$ npm list | grep encrypt
├─┬ letsencrypt-express@1.1.5
│ ├─┬ letsencrypt@1.4.4

$ lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 14.04.4 LTS
Release:	14.04
Codename:	trusty
root@botathon:~/www/piq# 

```

and of course this gives

![image](https://cloud.githubusercontent.com/assets/514002/16887367/85870852-4a8e-11e6-8701-c6ba31f00aec.png)
