### ISSUE TITLE
[Question] How to set the common name of cirtificate.

### ISSUE THREAD

**Issue by RadianSmile** [Daplie/letsencrypt-express#59]
I serve my site with following code:
```javascript
...
var LEX = require('letsencrypt-express')
var DOMAIN = "programming101.cs.nccu.edu.tw" ;

var lex = LEX.create({
  configDir: require('os').homedir() + '/letsencrypt/etc'
, approveRegistration: function (hostname, cb) { 

  // I eliminate the 'if' expression
    cb(null, {
      domains: [DOMAIN]
    , email: 'craziestdavid@gmail.com' // user@example.com
    , agreeTos: true
    });
  }
});

lex.onRequest = app;

lex.listen([8000], [8001], function () {
  var protocol = ('requestCert' in this) ? 'https': 'http';
  console.log("Listening at " + protocol + '://localhost:' + this.address().port);
});
```

Security overview tab in Chrome developer tool showed : 
ERR_CERT_COMMON_NAME_INVALID

![image](https://cloud.githubusercontent.com/assets/3115785/16876176/8a0ae014-4ad5-11e6-925f-d8d57f8b6459.png)

and the Cirtificate look like: 
![image](https://cloud.githubusercontent.com/assets/3115785/16876240/b9f81814-4ad5-11e6-8586-62b40bbf0720.png)

The problem is the common name is different with my site URL.

My site URL is **programming101.cs.nccu.edu.tw**,and I don't know why the `common name` of the certificate is **loclahost.dapile.com**. What's the problem?

----

By the way, server shows following error log after the first https connection.

```
[DEBUG le/lib/core.js] registeryAsync err
Error: [Error] letiny-core: not 200 ok
    at bodyToError (/home/pm/pm-database/node_modules/letiny-core/lib/get-certificate.js:81:15)
    at /home/pm/pm-database/node_modules/letiny-core/lib/get-certificate.js:265:20
    at Request._callback (/home/pm/pm-database/node_modules/letiny-core/lib/acme-client.js:102:7)
    at Request.self.callback (/home/pm/pm-database/node_modules/request/request.js:200:22)
    at emitTwo (events.js:106:13)
    at Request.emit (events.js:191:7)
    at Request.<anonymous> (/home/pm/pm-database/node_modules/request/request.js:1067:10)
    at emitOne (events.js:101:20)
    at Request.emit (events.js:188:7)
    at IncomingMessage.<anonymous> (/home/pm/pm-database/node_modules/request/request.js:988:12)
    at emitNone (events.js:91:20)
    at IncomingMessage.emit (events.js:185:7)
    at endReadableNT (_stream_readable.js:934:12)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickDomainCallback (internal/process/next_tick.js:122:9)

```

**Comment by coolaj86** [comment]
`localhost.daplie.com` is a fallback (because you can't start an `https` server without some sort of default certificate).

Your problem was something else - probably that the LE server couldn't loop back to you with that domain on that IP address - hence the `not 200 OK` that comes from the LE validating server.
