### ISSUE TITLE
How can I fix error [LEX] no certs loaded for '<domain>' ?

### ISSUE THREAD

**Issue by MacgyverMartins** [Daplie/letsencrypt-express#70]
When I run my server using de ssl express exemple from readme, and access the https://domain. I got the error:

```
[LEX] no certs loaded for '<domain>'
[LE] fetch
[LEX] no certs loaded for '<domain>'
[LE] fetch
[LEX] no certs loaded for '<domain>'
[LE] fetch
[LEX] no certs loaded for '<domain>'
[LE] fetch
[LEX] no certs loaded for '<domain>'
[LE] fetch
[LEX] no certs loaded for '<domain>'
[LE] fetch
[LEX] fetch from disk result '<domain>':
undefined
Error: Cannot find module 'asn1js/org/pkijs/common'
    at Function.Module._resolveFilename (module.js:325:15)
    at Function.Module._load (module.js:276:25)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at certInfo.getCertInfo (/home/ec2-user/dashboard-crm/node_modules/letsencrypt-express/node_modules/letsencrypt/lib/cert-info.js:19:16)
    at /home/ec2-user/dashboard-crm/node_modules/letsencrypt-express/node_modules/letsencrypt/lib/common.js:96:20
    at tryCatcher (/home/ec2-user/dashboard-crm/node_modules/letsencrypt-express/node_modules/letsencrypt/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/home/ec2-user/dashboard-crm/node_modules/letsencrypt-express/node_modules/letsencrypt/node_modules/bluebird/js/release/promise.js:504:31)
    at Promise._settlePromise (/home/ec2-user/dashboard-crm/node_modules/letsencrypt-express/node_modules/letsencrypt/node_modules/bluebird/js/release/promise.js:561:18)
    at Promise._settlePromise0 (/home/ec2-user/dashboard-crm/node_modules/letsencrypt-express/node_modules/letsencrypt/node_modules/bluebird/js/release/promise.js:606:10)
    at Promise._settlePromises (/home/ec2-user/dashboard-crm/node_modules/letsencrypt-express/node_modules/letsencrypt/node_modules/bluebird/js/release/promise.js:685:18)
    at Promise._fulfill (/home/ec2-user/dashboard-crm/node_modules/letsencrypt-express/node_modules/letsencrypt/node_modules/bluebird/js/release/promise.js:630:18)
    at PromiseArray._resolve (/home/ec2-user/dashboard-crm/node_modules/letsencrypt-express/node_modules/letsencrypt/node_modules/bluebird/js/release/promise_array.js:125:19)
    at PromiseArray._promiseFulfilled (/home/ec2-user/dashboard-crm/node_modules/letsencrypt-express/node_modules/letsencrypt/node_modules/bluebird/js/release/promise_array.js:143:14)
    at Promise._settlePromise (/home/ec2-user/dashboard-crm/node_modules/letsencrypt-express/node_modules/letsencrypt/node_modules/bluebird/js/release/promise.js:566:26)
    at Promise._settlePromise0 (/home/ec2-user/dashboard-crm/node_modules/letsencrypt-express/node_modules/letsencrypt/node_modules/bluebird/js/release/promise.js:606:10)
```

**Comment by coolaj86** [comment]
For one it looks like you got the version that was missing a dependency `asn1js`, so first try installing that: `npm install asn1js`

Second, there's about to be a new version of `letsencrypt-express` with an entirely different codebase, but I just haven't finished testing yet. I'll post back here when I publish it (hopefully within a few hours).

**Comment by MacgyverMartins** [comment]
Thanks a lot man. this's working perfectly. o/
Can we close this issue?
