### ISSUE TITLE
Error: Cannot find module 'asn1js/org/pkijs/common'

### ISSUE THREAD

**Issue by mortie** [Daplie/letsencrypt-express#71]
This is a recent issue, presumably as a result of one of your dependencies changing. Anyways, here's the stack trace:

```
Error: Cannot find module 'asn1js/org/pkijs/common'
    at Function.Module._resolveFilename (module.js:339:15)
    at Function.Module._load (module.js:290:25)
    at Module.require (module.js:367:17)
    at require (internal/module.js:16:19)
    at certInfo.getCertInfo (/home/martin/src/tlsproxy/node_modules/letsencrypt/lib/cert-info.js:19:16)
    at /home/martin/src/tlsproxy/node_modules/letsencrypt/lib/common.js:96:20
    at tryCatcher (/home/martin/src/tlsproxy/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/home/martin/src/tlsproxy/node_modules/bluebird/js/release/promise.js:504:31)
    at Promise._settlePromise (/home/martin/src/tlsproxy/node_modules/bluebird/js/release/promise.js:561:18)
    at Promise._settlePromise0 (/home/martin/src/tlsproxy/node_modules/bluebird/js/release/promise.js:606:10)
    at Promise._settlePromises (/home/martin/src/tlsproxy/node_modules/bluebird/js/release/promise.js:685:18)
    at Promise._fulfill (/home/martin/src/tlsproxy/node_modules/bluebird/js/release/promise.js:630:18)
    at PromiseArray._resolve (/home/martin/src/tlsproxy/node_modules/bluebird/js/release/promise_array.js:125:19)
    at PromiseArray._promiseFulfilled (/home/martin/src/tlsproxy/node_modules/bluebird/js/release/promise_array.js:143:14)
    at Promise._settlePromise (/home/martin/src/tlsproxy/node_modules/bluebird/js/release/promise.js:566:26)
    at Promise._settlePromise0 (/home/martin/src/tlsproxy/node_modules/bluebird/js/release/promise.js:606:10
```

This error occurs when letsencrypt-express tries to request a new certificate.

**Comment by mortie** [comment]
I've temporarily fixed this by changing your package.json's dependencies to include `"letsencrypt": "1.4.2"` instead of `"letsencrypt": "^1.4.2"`, which fixes the issue. The reason I'm reporting this here and not to the letsencrypt project directly is that "^1.4.2" doesn't match their newest version, 2.0.3, so it would be filing a bug report for an old version.

**Comment by coolaj86** [comment]
Same as https://github.com/Daplie/letsencrypt-express/issues/72

Fixed. Just reinstall.
