### ISSUE TITLE
No method createSecureContext

### ISSUE THREAD

**Issue by Coolomina** [Daplie/letsencrypt-express#84]
Hi there!,

I'm getting this error when running `$ sudo npm start` on the basic example of `app.js` provided. Any clues?, I'm currently using node v6.4.0 and tried the same with v6.2.2 and v.4.5.0. No changes.

> /home/rhcsa/WebstormProjects/https/node_modules/localhost.daplie.com-certificates/lib/index.js:21
var secureContext = require('tls').createSecureContext(tlsOptions);
                                   ^
TypeError: Object #<Object> has no method 'createSecureContext'
    at Object.<anonymous> (/home/rhcsa/WebstormProjects/https/node_modules/localhost.daplie.com-certificates/lib/index.js:21:36)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.LE.create (/home/rhcsa/WebstormProjects/https/node_modules/letsencrypt/index.js:240:23)
    at Object.module.exports.create (/home/rhcsa/WebstormProjects/https/node_modules/letsencrypt-express/lex.js:6:35)
    at Object.<anonymous> (/home/rhcsa/WebstormProjects/https/app.js:61:32)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Function.Module.runMain (module.js:497:10)
    at startup (node.js:119:16)

Thanks in advance!

**Comment by Seikho** [comment]
This doesn't look like you're actually using Node v6. You may want to check what version you're using by printing `process.version` to the console.

**Comment by coolaj86** [comment]
Agreed. See https://nodejs.org/api/tls.html#tls_tls_createsecurecontext_options. The method is part of node's API.

Perhaps you're using nvm or another version manager and the configuration is incorrect and still using an old version.

**Comment by Coolomina** [comment]
Shame on me guys. I didn't update the symbolic link between `/usr/local/n/versions/node/VERSION/bin/node` and `/usr/bin/node` when updating. 

Thanks for the feedback!, you can delete this thread if you want as it's not letsencrpyt related.

**Comment by coolaj86** [comment]
You're welcome. :)
