### ISSUE TITLE
Cannot get "staging" to work. Error: "DNS name does not have enough labels"

### ISSUE THREAD

**Issue by EvNaverniouk** [Daplie/letsencrypt-express#86]
I was able to to get `letsencrypt-express` to work just fine on production using real certificates, but I cannot for the life of me get it to work with localhost. Can you please offer some advice?

Im running my local server on Windows 10. Using node 6.5.0 and `letsencrypt-express` v2.0.3

My KOA server code (configured to run on `http://localhost:80`):

```
import lex from 'letsencrypt-express';

const le = lex.create({
		approveDomains (opts, certs, cb) {
			opts.domains = certs && certs.altnames || opts.domains;
			opts.email = 'HIDDEN';
			opts.agreeTos = true;

			cb(null, {
				certs,
				options: opts
			});
		},
		configDir: `${require('os').homedir()}/letsencrypt/etc`,
		debug: true,
		server: "staging"
	});

	const server = https.createServer(le.httpsOptions, le.middleware(app.callback()));

	server.listen(443, () => {	});

	const redirectHttps = koa().use(koaSSLify()).callback();
	http.createServer(le.middleware(redirectHttps)).listen(port, () => {});
```

And the full debug output from node is:

```
[le/index.js] le.getCertificates called for localhost with certs for NONE
[le/index.js] le.approveDomains called with certs for NONE and options:
[le/index.js] { domain: 'localhost',
  domains: [ 'localhost' ],
  email: 'HIDDEN',
  agreeTos: true }
[le/index.js] le getting from disk or registering new
[le/lib/core.js] checkAsync failed to find certificates
[le-store-certbot] success reading arg.accountsDir
[le-store-certbot] regrs.length 1
[le-store-certbot] accountId: 4a933a7258e83d17a38251354ac0cd21
[le/lib/core.js] calling le.acme.getCertificateAsync [ 'localhost' ]
undefined { Error: [Error] letiny-core: not 200 ok
    at bodyToError (R:\website\node_modules\le-acme-core\lib\get-certificate.js:55:15)
    at R:\website\node_modules\le-acme-core\lib\get-certificate.js:99:20
    at Request._callback (R:\website\node_modules\le-acme-core\lib\acme-client.js:113:7)
    at Request.self.callback (R:\node_modules\request\request.js:187:22)
    at emitTwo (events.js:106:13)
    at Request.emit (events.js:191:7)
    at Request.<anonymous> (R:\website\node_modules\request\request.js:1044:10)
    at emitOne (events.js:96:13)
    at Request.emit (events.js:188:7)
    at IncomingMessage.<anonymous> (R:\website\node_modules\request\request.js:965:12)
    at emitNone (events.js:91:20)
    at IncomingMessage.emit (events.js:185:7)
    at endReadableNT (_stream_readable.js:974:12)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickCallback (internal/process/next_tick.js:98:9)
  code: 'E_STATUS_CODE',
  type: 'urn:acme:error:malformed',
  description: 
   { type: 'urn:acme:error:malformed',
     detail: 'DNS name does not have enough labels',
     status: 400 },
  detail: 'DNS name does not have enough labels' } undefined
[le/index.js] le.getCertificates called for localhost with certs for NONE
[le/index.js] le.approveDomains called with certs for NONE and options:
[le/index.js] { domain: 'localhost',
  domains: [ 'localhost' ],
  email: 'HIDDEN',
  agreeTos: true }
[le/index.js] le getting from disk or registering new
[le/lib/core.js] checkAsync failed to find certificates
[le-store-certbot] success reading arg.accountsDir
[le-store-certbot] regrs.length 1
[le-store-certbot] accountId: 4a933a7258e83d17a38251354ac0cd21
[le/lib/core.js] calling le.acme.getCertificateAsync [ 'localhost' ]
undefined { Error: [Error] letiny-core: not 200 ok
    at bodyToError (R:\website\node_modules\le-acme-core\lib\get-certificate.js:55:15)
    at R:\website\node_modules\le-acme-core\lib\get-certificate.js:99:20
    at Request._callback (R:\website\node_modules\le-acme-core\lib\acme-client.js:113:7)
    at Request.self.callback (R:\website\node_modules\request\request.js:187:22)
    at emitTwo (events.js:106:13)
    at Request.emit (events.js:191:7)
    at Request.<anonymous> (R:\website\node_modules\request\request.js:1044:10)
    at emitOne (events.js:96:13)
    at Request.emit (events.js:188:7)
    at IncomingMessage.<anonymous> (R:\website\node_modules\request\request.js:965:12)
    at emitNone (events.js:91:20)
    at IncomingMessage.emit (events.js:185:7)
    at endReadableNT (_stream_readable.js:974:12)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickCallback (internal/process/next_tick.js:98:9)
  code: 'E_STATUS_CODE',
  type: 'urn:acme:error:malformed',
  description: 
   { type: 'urn:acme:error:malformed',
     detail: 'DNS name does not have enough labels',
     status: 400 },
  detail: 'DNS name does not have enough labels' } undefined
[le/index.js] le.getCertificates called for localhost with certs for NONE
[le/index.js] le.approveDomains called with certs for NONE and options:
[le/index.js] { domain: 'localhost',
  domains: [ 'localhost' ],
  email: 'HIDDEN',
  agreeTos: true }
[le/index.js] le getting from disk or registering new
[le/lib/core.js] checkAsync failed to find certificates
[le-store-certbot] success reading arg.accountsDir
[le-store-certbot] regrs.length 1
[le-store-certbot] accountId: 4a933a7258e83d17a38251354ac0cd21
```

**Comment by coolaj86** [comment]
`localhost` won't work. As per the RFC spec, `localhost` is disallowed for https.

For development you would need to set up `localhost.whatever.com` and use a `dns-01` strategy or have port-forwarding or tunneling to your machine to use the `http-01` strategy.

I happen to be working on adding this functionality to `serve-https` right now so that you would be able to use `<<user>>.daplie.me` for development.

**Comment by coolaj86** [comment]
Closed due to inactivity. Reopen if there's more to discuss.

**Comment by Altiano** [comment]
@coolaj86 How to "set up localhost.whatever.com and use a dns-01 strategy".

I am developing on windows machine and just get started using let's encrypt

**Comment by coolaj86** [comment]
Sorry I'm just now seeing this. We have two modules. One is manual dns the other is dynamic dns, which only works with daplie dns at the moment (which is in private beta and I can give you access).

With the manual process it will spit out a dns validation code and you have to add it as a txt record wherever you're hosting your dns (perhaps name.com or dyndns.org, whatever).

**Comment by coolaj86** [comment]
Also, this should probably be its own issues / question.
