### ISSUE TITLE
ERROR in le-sni-auto, Unapproved domain

### ISSUE THREAD

**Issue by julienvincent** [Daplie/letsencrypt-express#87]
I cannot get this to work in any way. event the bait example does not seem to work. When I attempt to hit the server, it throws the following error:

```
ERROR in le-sni-auto:
Error: unapproved domain
    at Object.le.approveDomains (/Users/julienvincent/code/yumo/frontend/src/node_modules/letsencrypt/index.js:201:14)
    at Object.le.getCertificates (/Users/julienvincent/code/yumo/frontend/src/node_modules/letsencrypt/index.js:210:12)
    at Object.tryCatcher (/Users/julienvincent/code/yumo/frontend/src/node_modules/bluebird/js/release/util.js:16:23)
    at Object.ret [as getCertificatesAsync] (eval at <anonymous> (/Users/julienvincent/code/yumo/frontend/src/node_modules/bluebird/js/release/promisify.js:184:12), <anonymous>:13:39)
    at TLSSocket._autoSni.sniCallback [as _SNICallback] (/Users/julienvincent/code/yumo/frontend/src/node_modules/le-sni-auto/index.js:107:27)
    at loadSNI (_tls_wrap.js:91:8)
    at TLSSocket.oncertcb (_tls_wrap.js:164:3)
    at TLSWrap.ssl.oncertcb (_tls_wrap.js:401:39)
```

**Comment by julienvincent** [comment]
My mistake - didn't realize this meant the domain I was hitting was not in the approvedDomains array.

**Comment by agoransson** [comment]
I have this very problem on an express app served from a subdomain with an alternate IP (not the same as the main domain IP). The DNS is updated and is pointing to the correct server.

What am I doing wrong here?

```
node: v6.9.2
npm: 3.10.9
ubuntu: 16.04
```


app.js

```
'use strict';

require('letsencrypt-express').create({

  server: 'https://acme-v01.api.letsencrypt.org/directory'

, email: 'my.private@email.se'

, agreeTos: true

, approveDomains: [ 'sub.domain.se' ]

, app: require('express')().use('/', function (req, res) {
    res.end('The Hello, World app is not really working');
  })

}).listen(80, 443);
```

package.json

```
{
  "name": "testar",
  "version": "1.0.0",
  "description": "",
  "main": "index.js",
  "scripts": {
    "start": "node app.js"
  },
  "author": "Me!",
  "license": "ISC",
  "dependencies": {
    "express": "^4.14.0",
    "letsencrypt-express": "^2.0.5"
  }
}
```

output:

```
> testar@1.0.0 start /home/ubuntu/testar
> node app.js

le.challenges[http-01].loopback should be defined as function (opts, domain, token, keyAuthorization, cb) { ... } and should prove (by external means) that the ACME server challenge 'http-01' will succeed
le.challenges[tls-sni-01].loopback should be defined as function (opts, domain, token, keyAuthorization, cb) { ... } and should prove (by external means) that the ACME server challenge 'tls-sni-01' will succeed
Handling ACME challenges and redirecting to https on plain port 80
Handling ACME challenges and serving https 443
ERROR in le-sni-auto:
Error: unapproved domain
    at Object.le.approveDomains (/home/ubuntu/testar/node_modules/letsencrypt/index.js:215:14)
    at Object.le.getCertificates (/home/ubuntu/testar/node_modules/letsencrypt/index.js:224:12)
    at Object.tryCatcher (/home/ubuntu/testar/node_modules/bluebird/js/release/util.js:16:23)
    at Object.ret [as getCertificatesAsync] (eval at makeNodePromisifiedEval (/home/ubuntu/testar/node_modules/bluebird/js/release/promisify.js:184:12), <anonymous>:13:39)
    at TLSSocket.sniCallback [as _SNICallback] (/home/ubuntu/testar/node_modules/le-sni-auto/index.js:118:27)
    at loadSNI (_tls_wrap.js:91:8)
    at TLSSocket.oncertcb (_tls_wrap.js:164:3)
    at TLSWrap.ssl.oncertcb (_tls_wrap.js:418:39)
```

**Comment by coolaj86** [comment]
For anyone who come across this (it's quite frustrating), there's much better documentation and error handling in the latest version of the official project: https://git.coolaj86.com/coolaj86/greenlock-express.js

I wrapped node's `SNICallback` so that I can catch and report on most errors (by logging) rather than silently swallowing them.
