### ISSUE TITLE
CA unable to validate the file you provisioned

### ISSUE THREAD

**Issue by fareshan** [Daplie/letsencrypt-express#88]
I am getting this error:

ERROR in le-sni-auto:
Error: The CA was unable to validate the file you provisioned. 
 - https://acme-staging.api.letsencrypt.org/acme/challenge/t70FnJK6GdSJ32Ty9xKKo9uSYwdPNflelPl_XhJsxBM/15121508 [pending]
 - https://acme-staging.api.letsencrypt.org/acme/challenge/t70FnJK6GdSJ32Ty9xKKo9uSYwdPNflelPl_XhJsxBM/15121509 [invalid]
   Could not connect to dev.socketserver.markiapp.com
 - https://acme-staging.api.letsencrypt.org/acme/challenge/t70FnJK6GdSJ32Ty9xKKo9uSYwdPNflelPl_XhJsxBM/15121510 [pending]
    at handleErr (/home/fareshan/todoapp/node_modules/le-acme-core/lib/get-certificate.js:351:17)
    at ensureValidation (/home/fareshan/todoapp/node_modules/le-acme-core/lib/get-certificate.js:226:16)
    at Request._callback (/home/fareshan/todoapp/node_modules/le-acme-core/lib/get-certificate.js:208:13)
    at Request.self.callback (/home/fareshan/todoapp/node_modules/request/request.js:187:22)
    at emitTwo (events.js:87:13)
    at Request.emit (events.js:172:7)
    at Request.<anonymous> (/home/fareshan/todoapp/node_modules/request/request.js:1048:10)
    at emitOne (events.js:77:13)
    at Request.emit (events.js:169:7)
    at IncomingMessage.<anonymous> (/home/fareshan/todoapp/node_modules/request/request.js:969:12)
    at emitNone (events.js:72:20)
    at IncomingMessage.emit (events.js:166:7)
    at endReadableNT (_stream_readable.js:921:12)
    at nextTickCallbackWith2Args (node.js:442:9)
    at process._tickDomainCallback (node.js:397:17)
ERROR in le-sni-auto:
Error: 140654803097408:error:1408F119:SSL routines:SSL3_GET_RECORD:decryption failed or bad record mac:../deps/openssl/openssl/ssl/s3_pkt.c:532:

**Comment by fareshan** [comment]
i solved that error by adding:

// handles acme-challenge and redirects to https
require('http').createServer(lex.middleware(require('redirect-https')())).listen(80, function () {
  console.log("Listening for ACME http-01 challenges on", this.address());
});


and now I get this error:

[pyconf] WARN index past array length:
69 69 undefined
unexpected duplicate key 'keyPath': '/home/fareshantous/letsencrypt/etc/live/dev.socketserver.markiapp.com/privkey.pem'
unexpected duplicate key 'checkpoints': '0'
unexpected duplicate key 'account': '36c701a6b15d76b6533d981712857ef2'
unexpected duplicate key 'dev.socketserver.markiapp.com': '/tmp/acme-challenges'

**Comment by fareshan** [comment]
i solved it by deleting the files in /home/fareshan/letsencrypt/etc/live/
